/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { db, ensureMigrated } from '@/lib/db/client'
import { lead } from '@/lib/db/schema'
import { desc } from 'drizzle-orm'
import { leadCreateSchema } from '@/lib/validators/lead'


export async function GET() {

  await ensureMigrated()
  const rows = await db.select().from(lead).orderBy(desc(lead.createdAt))
  return Response.json({ data: rows })
}

export async function POST(req: Request) {

  await ensureMigrated()
  const body = await req.json().catch(() => null)
  const parsed = leadCreateSchema.safeParse(body)
  if (!parsed.success) return Response.json({ error: 'validation', details: parsed.error.flatten() }, { status: 400 })
  const result = await db.insert(lead).values({ ...parsed.data, createdAt: new Date() }).returning()

  return Response.json({ data: result[0] }, { status: 201 })
}
