/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { LeadsTable } from '@/components/generated/LeadsTable'


export default function Page() {
  return (
    <main className="min-h-screen bg-muted/20">
      <header className="mx-auto max-w-6xl px-4 pt-10"><h1 className="text-2xl font-semibold">{"Leads"}</h1></header>
      <LeadsTable />
    </main>
  )
}
