/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT - edit intent/app.intent.yaml and rebuild. */
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export function middleware(req: NextRequest) {
  const requestId = req.headers.get("x-request-id") ?? crypto.randomUUID();
  const correlationId = req.headers.get("x-correlation-id") ?? requestId;
  const res = NextResponse.next();
  res.headers.set("X-Request-Id", requestId);
  res.headers.set("X-Correlation-Id", correlationId);
  console.log(
    JSON.stringify({
      level: "info",
      type: "http_request",
      request_id: requestId,
      correlation_id: correlationId,
      method: req.method,
      path: req.nextUrl.pathname,
    }),
  );
  return res;
}

export const config = {
  matcher: ["/api/:path*"],
};
