import { dirname, join, resolve } from 'node:path'
import { mkdirSync, writeFileSync } from 'node:fs'
import { TARGETS } from '../registry.js'

export function runNewCommand(ctx) {
  const dirArg = (ctx.args[1] && !ctx.args[1].startsWith('--')) ? ctx.args[1] : ctx.flag('dir', null)
  if (!dirArg) {
    console.error('Usage: intentstack new <dir> [--target web_ts_minimal] [--name NAME] [--single-file]')
    process.exit(2)
  }
  const dir = resolve(dirArg)
  const target = ctx.flag('target', 'web_ts_minimal')
  if (!TARGETS[target]) {
    console.error(`Unknown target "${target}". Available: ${Object.keys(TARGETS).join(', ')}`)
    process.exit(2)
  }
  const name = ctx.flag('name', 'IntentStack App')
  const id = ctx.flag('id', name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '') || 'intentstack_app')
  mkdirSync(join(dir, 'intent'), { recursive: true })
  writeFileSync(join(dir, 'intentstack.config.yaml'), `intent: intent/app.intent.yaml\nout: app\ntarget: ${target}\n`)
  if (ctx.has('--single-file')) writeFileSync(join(dir, 'intent/app.intent.yaml'), sampleIntent({ id, name, target }))
  else writeSampleModularIntent(dir, { id, name, target })
  console.log(`\nok created IntentStack project -> ${dir}`)
  console.log('Next:  node <path-to-intentstack>/src/index.js check --project ' + dir)
}

function writeSampleModularIntent(dir, { id, name, target }) {
  const files = {
    'intent/app.intent.yaml': `version: 0.1

project:
  id: ${id}
  name: ${name}
  target: ${target}

includes:
  - shared/*.yaml
  - backend/entities/*.yaml
  - backend/actions/*.yaml
  - frontend/pages/*.yaml
  - frontend/sections/**/*.yaml
`,
    'intent/shared/theme.yaml': `theme:
  preset: minimal
  radius: md
  density: comfortable
  color: neutral
`,
    'intent/shared/navigation.yaml': `navigation:
  logo: ${name}
  items:
    - label: Home
      href: /
    - label: Contact
      href: "#lead_form"
    - label: Leads
      href: /dashboard/leads
`,
    'intent/backend/entities/lead.entity.yaml': `entity:
  id: Lead
  table: leads
  fields:
    - id: name
      type: string
      label: Name
      required: true
    - id: email
      type: string
      label: Email
      required: true
    - id: message
      type: text
      label: Message
      required: false
    - id: status
      type: enum
      values: [new, contacted, closed]
      default: new
`,
    'intent/backend/actions/create-lead.action.yaml': `action:
  id: create_lead
  type: create_record
  entity: Lead
`,
    'intent/backend/actions/list-leads.action.yaml': `action:
  id: list_leads
  type: list_records
  entity: Lead
`,
    'intent/frontend/pages/home.page.yaml': `page:
  id: home
  path: /
  layout: landing
  sections:
    - ref: hero
    - ref: lead_form
    - ref: footer
`,
    'intent/frontend/pages/dashboard-leads.page.yaml': `page:
  id: dashboard_leads
  path: /dashboard/leads
  layout: dashboard
  title: Leads
  sections:
    - ref: leads_table
`,
    'intent/frontend/sections/home/hero.section.yaml': `section:
  id: hero
  type: hero
  title: ${name}
  subtitle: Generated from modular intent files.
  actions:
    - label: Contact
      kind: primary
      target: "#lead_form"
`,
    'intent/frontend/sections/home/lead-form.section.yaml': `section:
  id: lead_form
  type: form
  title: Contact
  entity: Lead
  fields: [name, email, message]
  submit:
    action: create_lead
    success_message: Thanks. We will contact you soon.
`,
    'intent/frontend/sections/home/footer.section.yaml': `section:
  id: footer
  type: footer
  text: Generated by IntentStack.
`,
    'intent/frontend/sections/dashboard/leads-table.section.yaml': `section:
  id: leads_table
  type: table
  entity: Lead
  source:
    action: list_leads
  columns: [name, email, status]
`,
  }
  for (const [rel, content] of Object.entries(files)) {
    const file = join(dir, ...rel.split('/'))
    mkdirSync(dirname(file), { recursive: true })
    writeFileSync(file, content)
  }
}

function sampleIntent({ id, name, target }) {
  return `version: 0.1

project:
  id: ${id}
  name: ${name}
  target: ${target}

theme:
  preset: minimal
  radius: md
  density: comfortable
  color: neutral

navigation:
  logo: ${name}
  items:
    - label: Home
      href: /
    - label: Contact
      href: "#lead_form"
    - label: Leads
      href: /dashboard/leads

entities:
  - id: Lead
    table: leads
    fields:
      - id: name
        type: string
        label: Name
        required: true
      - id: email
        type: string
        label: Email
        required: true
      - id: message
        type: text
        label: Message
        required: false
      - id: status
        type: enum
        values: [new, contacted, closed]
        default: new

actions:
  - id: create_lead
    type: create_record
    entity: Lead
  - id: list_leads
    type: list_records
    entity: Lead

pages:
  - id: home
    path: /
    layout: landing
    sections:
      - id: hero
        type: hero
        title: ${name}
        subtitle: Generated from one intent file.
        actions:
          - label: Contact
            kind: primary
            target: "#lead_form"
      - id: lead_form
        type: form
        title: Contact
        entity: Lead
        fields: [name, email, message]
        submit:
          action: create_lead
          success_message: Thanks. We will contact you soon.
      - id: footer
        type: footer
        text: Generated by IntentStack.

  - id: dashboard_leads
    path: /dashboard/leads
    layout: dashboard
    title: Leads
    sections:
      - id: leads_table
        type: table
        entity: Lead
        source:
          action: list_leads
        columns: [name, email, status]
`
}
