/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { AppNav } from '@/components/generated/AppNav'
import { DocsContent } from '@/components/generated/DocsContent'
import { DocsComponentCards } from '@/components/generated/DocsComponentCards'
import { DocsComponentCardsCode } from '@/components/generated/DocsComponentCardsCode'
import { DocsComponentForm } from '@/components/generated/DocsComponentForm'
import { DocsComponentFormCode } from '@/components/generated/DocsComponentFormCode'
import { DocsComponentTable } from '@/components/generated/DocsComponentTable'
import { DocsComponentTableCode } from '@/components/generated/DocsComponentTableCode'
import { DocsComponentPricing } from '@/components/generated/DocsComponentPricing'
import { DocsComponentPricingCode } from '@/components/generated/DocsComponentPricingCode'
import { DocsComponentStats } from '@/components/generated/DocsComponentStats'
import { DocsComponentStatsCode } from '@/components/generated/DocsComponentStatsCode'
import { DocsFooter } from '@/components/generated/DocsFooter'


export default function Page() {
  return (
    <main className="min-h-screen bg-background">
      <AppNav />
      <DocsContent />
      <DocsComponentCards />
      <DocsComponentCardsCode />
      <DocsComponentForm />
      <DocsComponentFormCode />
      <DocsComponentTable />
      <DocsComponentTableCode />
      <DocsComponentPricing />
      <DocsComponentPricingCode />
      <DocsComponentStats />
      <DocsComponentStatsCode />
      <DocsFooter />
    </main>
  )
}
