/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { AppNav } from "@/components/generated/AppNav";
import { DocsContent } from "@/components/generated/DocsContent";
import { DocsFooter } from "@/components/generated/DocsFooter";

export default function Page() {
  return (
    <main className="min-h-screen bg-background">
      <AppNav />
      <DocsContent />
      <DocsFooter />
    </main>
  );
}
