/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { AppNav } from '@/components/generated/AppNav'
import { DocsContent } from '@/components/generated/DocsContent'
import { DocsComponentCards } from '@/components/generated/DocsComponentCards'
import { DocsComponentForm } from '@/components/generated/DocsComponentForm'
import { DocsComponentTable } from '@/components/generated/DocsComponentTable'
import { DocsComponentPricing } from '@/components/generated/DocsComponentPricing'
import { DocsComponentStats } from '@/components/generated/DocsComponentStats'
import { DocsFooter } from '@/components/generated/DocsFooter'


export default function Page() {
  return (
    <main className="min-h-screen bg-background">
      <AppNav />
      <DocsContent />
      <DocsComponentCards />
      <DocsComponentForm />
      <DocsComponentTable />
      <DocsComponentPricing />
      <DocsComponentStats />
      <DocsFooter />
    </main>
  )
}
