/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { z } from 'zod'

export const leadCreateSchema = z.object({
  name: z.string().min(1),
  phone: z.string().min(1),
  company: z.string().optional(),
  message: z.string().optional(),
  status: z.enum(['new', 'contacted', 'closed']).optional(),
})

export type LeadCreate = z.infer<typeof leadCreateSchema>
