-- @generated by IntentStack. Applied automatically on server start.

CREATE TABLE IF NOT EXISTS demo_requests (
  id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  project_type text NOT NULL,
  budget real,
  message text,
  created_at integer NOT NULL
);

