// Shared data-model codegen. Both targets use Drizzle + SQLite, so entity -> schema,
// validators and migration SQL are produced HERE and merely *placed* differently by each
// adapter. This is the concrete payoff of a target-agnostic IR: real codegen reuse.
import { snake } from '../util.js'

const q = (s) => `'${s}'`
const col = (id) => snake(id)

const DRIZZLE = {
  string: (f) => `text(${q(col(f.id))})`,
  text: (f) => `text(${q(col(f.id))})`,
  enum: (f) => `text(${q(col(f.id))})`,
  number: (f) => `real(${q(col(f.id))})`,
  boolean: (f) => `integer(${q(col(f.id))}, { mode: 'boolean' })`,
  datetime: (f) => `integer(${q(col(f.id))}, { mode: 'timestamp' })`,
}
const SQLTYPE = { string: 'text', text: 'text', enum: 'text', number: 'real', boolean: 'integer', datetime: 'integer' }

export const schemaImports = () => `import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core'\n`

export function schemaBody(graph) {
  let out = ''
  for (const e of graph.entities) {
    out += `\nexport const ${e.id.toLowerCase()} = sqliteTable(${q(e.table || e.id.toLowerCase())}, {\n`
    out += `  id: integer('id').primaryKey({ autoIncrement: true }),\n`
    for (const f of e.fields || []) {
      let line = `  ${f.id}: ` + (DRIZZLE[f.type] || DRIZZLE.string)(f)
      if (f.required) line += `.notNull()`
      if (f.default !== undefined) line += `.default(${typeof f.default === 'string' ? q(f.default) : f.default})`
      out += line + `,\n`
    }
    out += `  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),\n`
    out += `})\n`
  }
  return out
}

export function migrationSql(graph) {
  let out = '-- @generated by IntentStack. Applied automatically on server start.\n\n'
  for (const e of graph.entities) {
    out += `CREATE TABLE IF NOT EXISTS ${e.table || e.id.toLowerCase()} (\n`
    const lines = ['  id integer PRIMARY KEY AUTOINCREMENT NOT NULL']
    for (const f of e.fields || []) {
      let l = `  ${col(f.id)} ${SQLTYPE[f.type] || 'text'}`
      if (f.default !== undefined) l += ` DEFAULT ${typeof f.default === 'string' ? `'${f.default}'` : f.default}`
      if (f.required) l += ' NOT NULL'
      lines.push(l)
    }
    lines.push('  created_at integer NOT NULL')
    out += lines.join(',\n') + '\n);\n\n'
  }
  return out
}

function zodFor(f) {
  let z
  switch (f.type) {
    case 'number': z = 'z.coerce.number()'; break
    case 'boolean': z = 'z.coerce.boolean()'; break
    case 'enum': z = `z.enum([${(f.values || []).map((v) => q(v)).join(', ')}])`; break
    case 'datetime': z = 'z.coerce.date()'; break
    default: z = 'z.string()' + (f.required ? '.min(1)' : '')
  }
  if (!f.required) z += '.optional()'
  return z
}

export function validatorBody(e) {
  let out = `import { z } from 'zod'\n\n`
  out += `export const ${e.id.toLowerCase()}CreateSchema = z.object({\n`
  for (const f of e.fields || []) out += `  ${f.id}: ${zodFor(f)},\n`
  out += `})\n\nexport type ${e.id}Create = z.infer<typeof ${e.id.toLowerCase()}CreateSchema>\n`
  return out
}

// Which client functions an entity needs, derived from its record actions.
export function entityClientNeeds(graph) {
  const byEntity = {}
  for (const a of graph.actions) {
    if (!a.entity) continue
    ;(byEntity[a.entity] ||= new Set()).add(a.type)
  }
  return byEntity
}
