// Database driver abstraction. Targets consume schema, migration, client and
// package metadata through this contract instead of embedding SQLite details.

import { createHash } from 'node:crypto'
import { snake } from '../util.js'

const q = (s) => `'${s}'`
const col = (id) => snake(id)

const SQLITE_DRIZZLE = {
  string: (f) => `text(${q(col(f.id))})`,
  text: (f) => `text(${q(col(f.id))})`,
  enum: (f) => `text(${q(col(f.id))})`,
  number: (f) => `real(${q(col(f.id))})`,
  boolean: (f) => `integer(${q(col(f.id))}, { mode: 'boolean' })`,
  datetime: (f) => `integer(${q(col(f.id))}, { mode: 'timestamp' })`,
}
const SQLITE_SQLTYPE = { string: 'text', text: 'text', enum: 'text', number: 'real', boolean: 'integer', datetime: 'integer' }

export const DB_DRIVERS = {
  sqlite: {
    id: 'sqlite',
    label: 'SQLite/libSQL',
    migrationFile: 'migrations/0000_init.sql',
    manifestFile: 'migrations/manifest.json',
    packageDependencies: {
      '@libsql/client': '^0.14.0',
      'drizzle-orm': '^0.36.4',
    },
    schemaImports: sqliteSchemaImports,
    schemaBody: sqliteSchemaBody,
    migrationSql: sqliteMigrationSql,
    migrationManifest,
    clientTs: sqliteClientTs,
    envExampleLines: () => [
      'DB_URL=file:./data.db',
      '# INTENTSTACK_AUTO_MIGRATE=false   # production: run npm run migrate during deploy',
    ],
    readmeDatabase: () => `The generated app reads \`migrations/manifest.json\` and applies listed SQL migrations to a
local SQLite file (\`data.db\`) on boot. For production deploys, set
\`INTENTSTACK_AUTO_MIGRATE=false\` and run \`npm run migrate\` as a separate deploy step.`,
    gitignore: ['*.db', 'data.db'],
  },
}

export const DATABASE_DRIVER_IDS = Object.keys(DB_DRIVERS)

export function dbDriver(graph) {
  const id = graph.database?.driver || graph.project?.database?.driver || 'sqlite'
  const driver = DB_DRIVERS[id]
  if (!driver) throw new Error(`Unsupported database driver "${id}". Available: ${Object.keys(DB_DRIVERS).join(', ')}`)
  return driver
}

function sqliteSchemaImports() {
  return `import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core'\n`
}

function sqliteSchemaBody(graph) {
  let out = ''
  for (const e of graph.entities) {
    out += `\nexport const ${e.id.toLowerCase()} = sqliteTable(${q(e.table || e.id.toLowerCase())}, {\n`
    out += `  id: integer('id').primaryKey({ autoIncrement: true }),\n`
    if (graph.tenancy?.enabled === true) out += `  tenantId: text('tenant_id').notNull(),\n`
    for (const f of e.fields || []) {
      let line = `  ${f.id}: ` + (SQLITE_DRIZZLE[f.type] || SQLITE_DRIZZLE.string)(f)
      if (f.required) line += `.notNull()`
      if (f.default !== undefined) line += `.default(${typeof f.default === 'string' ? q(f.default) : f.default})`
      out += line + `,\n`
    }
    out += `  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),\n`
    out += `})\n`
  }
  return out
}

function sqliteMigrationSql(graph) {
  let out = '-- @generated by IntentStack. Applied automatically on server start.\n\n'
  for (const e of graph.entities) {
    out += `CREATE TABLE IF NOT EXISTS ${e.table || e.id.toLowerCase()} (\n`
    const lines = ['  id integer PRIMARY KEY AUTOINCREMENT NOT NULL']
    if (graph.tenancy?.enabled === true) lines.push('  tenant_id text NOT NULL')
    for (const f of e.fields || []) {
      let l = `  ${col(f.id)} ${SQLITE_SQLTYPE[f.type] || 'text'}`
      if (f.default !== undefined) l += ` DEFAULT ${typeof f.default === 'string' ? `'${f.default}'` : f.default}`
      if (f.required) l += ' NOT NULL'
      lines.push(l)
    }
    lines.push('  created_at integer NOT NULL')
    out += lines.join(',\n') + '\n);\n\n'
  }
  return out
}

function migrationManifest(graph) {
  const driver = dbDriver(graph)
  const initSql = driver.migrationSql(graph)
  return JSON.stringify({
    version: 1,
    driver: driver.id,
    migrations: [
      {
        id: '0000_init',
        file: '0000_init.sql',
        checksum: checksum(initSql),
      },
    ],
  }, null, 2) + '\n'
}

function sqliteClientTs({ banner, pathImports, pathPrelude = '', migrationManifestPathExpr, functionName, memoized }) {
  const runner = memoized
    ? `let migrated: Promise<void> | null = null
export async function runIntentStackMigrations() {
  await runMigrations()
}

export function ${functionName}() {
  if (process.env.INTENTSTACK_AUTO_MIGRATE === 'false') return Promise.resolve()
  if (!migrated) migrated = runMigrations()
  return migrated
}
`
    : `export async function runIntentStackMigrations() {
  await runMigrations()
}

export async function ${functionName}() {
  if (process.env.INTENTSTACK_AUTO_MIGRATE === 'false') return
  await runMigrations()
}
`
  return banner + `import { drizzle } from 'drizzle-orm/libsql'
import { createClient } from '@libsql/client'
import { readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
${pathImports}

const url = process.env.DB_URL ?? 'file:./data.db'
export const client = createClient({ url })
export const db = drizzle(client)
${pathPrelude}
type MigrationManifest = {
  migrations?: Array<{ id: string; file: string; checksum?: string }>
}

const MIGRATION_MANIFEST = ${migrationManifestPathExpr}

function migrationEntries() {
  const manifest = JSON.parse(readFileSync(MIGRATION_MANIFEST, 'utf8')) as MigrationManifest
  return (manifest.migrations || []).map((migration) => ({
    id: migration.id,
    path: join(dirname(MIGRATION_MANIFEST), migration.file),
    checksum: migration.checksum,
  }))
}

async function ensureMigrationTable() {
  await client.execute(\`
    CREATE TABLE IF NOT EXISTS __intentstack_migrations (
      id text PRIMARY KEY NOT NULL,
      checksum text NOT NULL,
      applied_at text NOT NULL
    )
  \`)
}

function checksum(sql: string) {
  return createHash('sha256').update(sql).digest('hex')
}

async function migrationRecord(id: string) {
  const result = await client.execute({ sql: 'SELECT checksum FROM __intentstack_migrations WHERE id = ?', args: [id] })
  return result.rows[0] as { checksum?: string } | undefined
}

async function markApplied(id: string, hash: string) {
  await client.execute({
    sql: 'INSERT INTO __intentstack_migrations (id, checksum, applied_at) VALUES (?, ?, ?)',
    args: [id, hash, new Date().toISOString()],
  })
}

async function runMigrations() {
  await ensureMigrationTable()
  for (const migration of migrationEntries()) {
    const sql = readFileSync(migration.path, 'utf8')
    const hash = checksum(sql)
    if (migration.checksum && migration.checksum !== hash) throw new Error(\`Migration \${migration.id} does not match manifest checksum.\`)
    const existing = await migrationRecord(migration.id)
    if (existing) {
      if (existing.checksum !== hash) throw new Error(\`Migration \${migration.id} was already applied with a different checksum.\`)
      continue
    }
    await client.executeMultiple(sql)
    await markApplied(migration.id, hash)
  }
}

${runner}`
}

function checksum(sql) {
  return createHash('sha256').update(sql).digest('hex')
}
