/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { AppNav } from '@/components/generated/AppNav'
import { Hero } from '@/components/generated/Hero'
import { Process } from '@/components/generated/Process'
import { Footer } from '@/components/generated/Footer'


export default function Page() {
  return (
    <main className="min-h-screen bg-background">
      <AppNav />
      <Hero />
      <Process />
      <Footer />
    </main>
  )
}
