/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { db, ensureMigrated } from '@/lib/db/client'
import { lead } from '@/lib/db/schema'
import { eq } from 'drizzle-orm'
import { leadCreateSchema } from '@/lib/validators/lead'

type Ctx = { params: { id: string } }

export async function GET(_req: Request, { params }: Ctx) {

  await ensureMigrated()
  const rows = await db.select().from(lead).where(eq(lead.id, Number(params.id)))
  if (rows.length === 0) return Response.json({ error: 'not_found' }, { status: 404 })
  return Response.json({ data: rows[0] })
}

export async function PUT(req: Request, { params }: Ctx) {

  await ensureMigrated()
  const body = await req.json().catch(() => null)
  const parsed = leadCreateSchema.partial().safeParse(body)
  if (!parsed.success) return Response.json({ error: 'validation', details: parsed.error.flatten() }, { status: 400 })
  const result = await db.update(lead).set(parsed.data).where(eq(lead.id, Number(params.id))).returning()
  if (result.length === 0) return Response.json({ error: 'not_found' }, { status: 404 })

  return Response.json({ data: result[0] })
}
