/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { db, ensureMigrated } from "@/lib/db/client";
import { demorequest } from "@/lib/db/schema";
import { desc } from "drizzle-orm";
import { demorequestCreateSchema } from "@/lib/validators/demorequest";

export async function GET() {
  await ensureMigrated();
  const rows = await db
    .select()
    .from(demorequest)
    .orderBy(desc(demorequest.createdAt));
  return Response.json({ data: rows });
}

export async function POST(req: Request) {
  await ensureMigrated();
  const body = await req.json().catch(() => null);
  const parsed = demorequestCreateSchema.safeParse(body);
  if (!parsed.success)
    return Response.json(
      { error: "validation", details: parsed.error.flatten() },
      { status: 400 },
    );
  const result = await db
    .insert(demorequest)
    .values({ ...parsed.data, createdAt: new Date() })
    .returning();

  return Response.json({ data: result[0] }, { status: 201 });
}
