/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
function csrfToken() {
  if (typeof document === "undefined") return "";
  const match = document.cookie
    .split("; ")
    .find((part) => part.startsWith("intentstack_csrf="));
  return match ? decodeURIComponent(match.split("=").slice(1).join("=")) : "";
}

function csrfHeaders(): Record<string, string> {
  const token = csrfToken();
  return token ? { "X-CSRF-Token": token } : {};
}

export async function createDemoRequest(payload: Record<string, unknown>) {
  const res = await fetch("/api/demo_requests", {
    method: "POST",
    credentials: "include",
    headers: { "Content-Type": "application/json", ...csrfHeaders() },
    body: JSON.stringify(payload),
  });
  const json = await res.json().catch(() => ({}));
  return { ok: res.ok, data: json.data, error: json.error };
}

export async function listDemoRequest(): Promise<
  Array<Record<string, unknown>>
> {
  const res = await fetch("/api/demo_requests", {
    cache: "no-store",
    credentials: "include",
  });
  const json = await res.json().catch(() => ({ data: [] }));
  return (json.data ?? []) as Array<Record<string, unknown>>;
}
