/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
export async function createDemoRequest(payload: Record<string, unknown>) {
  const res = await fetch('/api/demo_requests', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  })
  const json = await res.json().catch(() => ({}))
  return { ok: res.ok, data: json.data, error: json.error }
}

export async function listDemoRequest(): Promise<Array<Record<string, unknown>>> {
  const res = await fetch('/api/demo_requests', { cache: 'no-store' })
  const json = await res.json().catch(() => ({ data: [] }))
  return (json.data ?? []) as Array<Record<string, unknown>>
}

