import { col, q, SQLITE_DRIZZLE, SQLITE_SQLTYPE, schemaSnapshot, schemaChecksum } from './common.js'
import { migrationRuntimeTs } from './migration_runtime.js'

export const sqlite = {
  id: 'sqlite',
  label: 'SQLite/libSQL',
  migrationFile: 'migrations/0000_init.sql',
  manifestFile: 'migrations/manifest.json',
  packageDependencies: {
    '@libsql/client': '^0.14.0',
    'drizzle-orm': '^0.36.4',
  },
  schemaSnapshot: (graph) => schemaSnapshot(graph),
  schemaChecksum,
  schemaImports,
  schemaBody,
  migrationSql,
  rollbackMigrationSql,
  diffMigrationSql,
  clientTs,
  migrationRuntimeTs: (banner) => migrationRuntimeTs({ banner, driver: 'sqlite' }),
  envExampleLines: () => [
    'DB_URL=file:./data.db',
    '# INTENTSTACK_AUTO_MIGRATE=false   # production: run npm run migrate during deploy',
  ],
  readmeDatabase: () => `The generated app reads \`migrations/manifest.json\` and applies listed SQL migrations to a
local SQLite file (\`data.db\`) on boot. For production deploys, set
\`INTENTSTACK_AUTO_MIGRATE=false\` and run \`npm run migrate\` as a separate deploy step.`,
  gitignore: ['*.db', 'data.db'],
}

function schemaImports() {
  return "import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core'\n"
}

function schemaBody(graph) {
  let out = ''
  for (const e of graph.entities) {
    out += `\nexport const ${e.id.toLowerCase()} = sqliteTable(${q(e.table || e.id.toLowerCase())}, {\n`
    out += `  id: integer('id').primaryKey({ autoIncrement: true }),\n`
    if (graph.tenancy?.enabled === true) out += `  tenantId: text('tenant_id').notNull(),\n`
    for (const f of e.fields || []) {
      let line = `  ${f.id}: ` + (SQLITE_DRIZZLE[f.type] || SQLITE_DRIZZLE.string)(f)
      if (f.required) line += '.notNull()'
      if (f.default !== undefined) line += `.default(${typeof f.default === 'string' ? q(f.default) : f.default})`
      out += `${line},\n`
    }
    out += "  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),\n"
    out += '})\n'
  }
  return out
}

function migrationSql(graph) {
  let out = '-- @generated by IntentStack. Applied automatically on server start.\n\n'
  for (const e of graph.entities) {
    out += `CREATE TABLE IF NOT EXISTS ${e.table || e.id.toLowerCase()} (\n`
    const lines = ['  id integer PRIMARY KEY AUTOINCREMENT NOT NULL']
    if (graph.tenancy?.enabled === true) lines.push('  tenant_id text NOT NULL')
    for (const f of e.fields || []) {
      let line = `  ${col(f.id)} ${SQLITE_SQLTYPE[f.type] || 'text'}`
      if (f.default !== undefined) line += ` DEFAULT ${typeof f.default === 'string' ? `'${f.default}'` : f.default}`
      if (f.required) line += ' NOT NULL'
      lines.push(line)
    }
    lines.push('  created_at integer NOT NULL')
    out += `${lines.join('\n')}\n);\n\n`
  }
  out += sqliteSessionTableSql()
  return out
}

function diffMigrationSql(previous, current) {
  const statements = []
  const previousEntities = new Map((previous?.entities || []).map((entity) => [entity.id, entity]))
  for (const entity of current.entities || []) {
    const before = previousEntities.get(entity.id)
    if (!before) {
      statements.push(sqliteCreateTableFromSnapshot(entity))
      continue
    }
    const previousFields = new Map((before.fields || []).map((field) => [field.id, field]))
    for (const field of entity.fields || []) {
      if (previousFields.has(field.id)) continue
      statements.push(sqliteAddColumn(entity, field))
    }
    for (const field of before.fields || []) {
      const next = (entity.fields || []).find((item) => item.id === field.id)
      if (!next) statements.push(`-- Column ${field.column} was removed from intent for table ${entity.table}. SQLite keeps existing columns; create a manual data migration before dropping it.`)
      else if (field.type !== next.type) statements.push(`-- Column ${field.column} changed type from ${field.type} to ${next.type}. SQLite requires a manual table rebuild for type changes.`)
    }
  }
  for (const entity of previous?.entities || []) {
    if (!(current.entities || []).some((item) => item.id === entity.id)) {
      statements.push(`-- Table ${entity.table} was removed from intent. IntentStack does not drop tables automatically.`)
    }
  }
  if (statements.length === 0) statements.push('-- No database changes detected.')
  return `-- @generated by IntentStack. Schema evolution migration.\n\n${statements.join('\n\n')}\n`
}

function rollbackMigrationSql(previous, current) {
  const statements = []
  const previousEntities = new Map((previous?.entities || []).map((entity) => [entity.id, entity]))
  for (const entity of current.entities || []) {
    const before = previousEntities.get(entity.id)
    if (!before) {
      statements.push(`DROP TABLE IF EXISTS ${entity.table};`)
      continue
    }
    const previousFields = new Map((before.fields || []).map((field) => [field.id, field]))
    for (const field of entity.fields || []) {
      if (!previousFields.has(field.id) && !field.primary_key) statements.push(`ALTER TABLE ${entity.table} DROP COLUMN ${field.column};`)
    }
  }
  if (!previous?.entities?.length) statements.push('DROP TABLE IF EXISTS __intentstack_sessions;')
  if (statements.length === 0) statements.push('-- No automatic rollback is available for this migration.')
  return `-- @generated by IntentStack. Rollback migration.\n\n${statements.join('\n\n')}\n`
}

function clientTs({ banner, pathImports, pathPrelude = '', migrationManifestPathExpr, functionName, memoized }) {
  const runner = memoized
    ? `let migrated: Promise<void> | null = null
export async function runIntentStackMigrations() {
  await runDbMigrations(client, MIGRATION_MANIFEST)
}

export function ${functionName}() {
  if (process.env.INTENTSTACK_AUTO_MIGRATE === 'false') return Promise.resolve()
  if (!migrated) migrated = runIntentStackMigrations()
  return migrated
}
`
    : `export async function runIntentStackMigrations() {
  await runDbMigrations(client, MIGRATION_MANIFEST)
}

export async function ${functionName}() {
  if (process.env.INTENTSTACK_AUTO_MIGRATE === 'false') return
  await runIntentStackMigrations()
}
`

  return banner + `import { drizzle } from 'drizzle-orm/libsql'
import { createClient } from '@libsql/client'
import { runDbMigrations, rollbackDbMigration, checkDbMigrationDrift } from './migration_runtime'
${pathImports}

const url = process.env.DB_URL ?? 'file:./data.db'
export const client = createClient({ url })
export const db = drizzle(client)
export async function checkDatabaseHealth() {
  await client.execute('SELECT 1')
  return true
}

export async function closeDatabase() {
  await Promise.resolve(client.close())
}
${pathPrelude}
const MIGRATION_MANIFEST = ${migrationManifestPathExpr}

export async function rollbackIntentStackMigration() {
  return rollbackDbMigration(client, MIGRATION_MANIFEST)
}

export async function checkIntentStackSchemaDrift() {
  return checkDbMigrationDrift(client, MIGRATION_MANIFEST)
}

${runner}`
}

function sqliteCreateTableFromSnapshot(entity) {
  const lines = (entity.fields || []).map((field) => `  ${field.column} ${sqliteSnapshotSqlType(field)}${sqliteColumnConstraints(field)}`)
  return `CREATE TABLE IF NOT EXISTS ${entity.table} (\n${lines.join('\n')}\n);`
}

function sqliteSnapshotSqlType(field) {
  return SQLITE_SQLTYPE[field.type] || field.type || 'text'
}

function sqliteColumnConstraints(field, opts = {}) {
  if (field.primary_key) return ' PRIMARY KEY AUTOINCREMENT NOT NULL'
  let out = ''
  const defaultValue = field.default !== undefined
    ? (typeof field.default === 'string' ? `'${field.default.replaceAll("'", "''")}'` : String(field.default))
    : (opts.forAddColumn && field.required ? fallbackDefault(field.type) : null)
  if (defaultValue != null) out += ` DEFAULT ${defaultValue}`
  if (field.required) out += ' NOT NULL'
  return out
}

function sqliteAddColumn(entity, field) {
  return `ALTER TABLE ${entity.table} ADD COLUMN ${field.column} ${sqliteSnapshotSqlType(field)}${sqliteColumnConstraints(field, { forAddColumn: true })};`
}

function fallbackDefault(type) {
  if (type === 'number') return '0'
  if (type === 'boolean') return '0'
  if (type === 'datetime') return '0'
  return "''"
}

function sqliteSessionTableSql() {
  return [
    'CREATE TABLE IF NOT EXISTS __intentstack_sessions (',
    '  id text PRIMARY KEY NOT NULL,',
    '  token_hash text NOT NULL,',
    '  user_id text,',
    '  role text NOT NULL,',
    '  csrf text NOT NULL,',
    '  expires_at integer NOT NULL,',
    '  revoked_at integer,',
    '  created_at integer NOT NULL,',
    '  rotated_at integer',
    ');',
    'CREATE INDEX IF NOT EXISTS __intentstack_sessions_expires_at_idx ON __intentstack_sessions (expires_at);',
    '',
  ].join('\n')
}
