/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT - edit intent/app.intent.yaml and rebuild. */
const startedAt = Date.now();
let requestsTotal = 0;

export async function GET() {
  requestsTotal += 1;
  const uptimeSeconds =
    typeof process.uptime === "function"
      ? process.uptime()
      : Math.round((Date.now() - startedAt) / 1000);
  return Response.json({
    ok: true,
    uptime_seconds: uptimeSeconds,
    started_at: new Date(startedAt).toISOString(),
    requests_total: requestsTotal,
  });
}
