import { ENTITY_ACTIONS } from './registry.js'
import { tenancyConfig } from './emit/shared/tenancy.js'

export function generateTestFiles(graph) {
  const operations = apiOperations(graph)
  return {
    'api-contract.test.mjs': apiContractTest(graph, operations),
    'README.md': testReadme(graph, operations),
  }
}

function apiOperations(graph) {
  const tenancy = tenancyConfig(graph)
  const out = [
    { action: 'health', method: 'GET', path: '/api/health', entity: 'Observability', idEnv: '', mutation: false, body: null, expected: [200], auth: false },
    { action: 'metrics', method: 'GET', path: '/api/metrics', entity: 'Observability', idEnv: '', mutation: false, body: null, expected: [200], auth: false },
  ]
  const byEntity = {}
  for (const action of graph.actions) {
    if (!action.entity || !ENTITY_ACTIONS.includes(action.type)) continue
    ;(byEntity[action.entity] ||= []).push(action)
  }
  for (const [entityId, actions] of Object.entries(byEntity)) {
    const entity = graph.getEntity(entityId)
    if (!entity) continue
    const base = entity.table || entity.id.toLowerCase()
    const action = (type) => actions.find((item) => item.type === type)
    const list = action('list_records')
    const create = action('create_record')
    const get = action('get_record')
    const update = action('update_record')
    const remove = action('delete_record')
    const subscribe = action('subscribe_records')
    if (list) out.push(operation(list, 'GET', `/api/${base}`, entity, { expected: [200], tenancy }))
    if (create) out.push(operation(create, 'POST', `/api/${base}`, entity, { mutation: true, body: samplePayload(entity), expected: [200, 201], tenancy }))
    if (get) out.push(operation(get, 'GET', `/api/${base}/{id}`, entity, { id: true, expected: [200, 404], tenancy }))
    if (update) out.push(operation(update, 'PUT', `/api/${base}/{id}`, entity, { id: true, mutation: true, body: samplePayload(entity, { partial: true }), expected: [200, 404], tenancy }))
    if (remove) out.push(operation(remove, 'DELETE', `/api/${base}/{id}`, entity, { id: true, mutation: true, expected: [200, 404], tenancy }))
    if (subscribe) out.push(operation(subscribe, 'GET', `/api/${base}/stream`, entity, { expected: [200], tenancy, stream: true }))
  }
  return out
}

function operation(action, method, path, entity, opts = {}) {
  return {
    action: action.id,
    method,
    path,
    entity: entity.id,
    idEnv: `INTENTSTACK_TEST_${envName(entity.id)}_ID`,
    mutation: opts.mutation === true,
    body: opts.body || null,
    expected: opts.expected || [200],
    auth: Boolean(action.auth && action.auth !== 'reserved'),
    tenancy: Boolean(opts.tenancy),
    tenantHeader: opts.tenancy?.header || '',
    stream: opts.stream === true,
  }
}

function apiContractTest(graph, operations) {
  const defaultBaseUrl = graph.project?.target === 'next_shadcn' ? 'http://localhost:3000' : 'http://localhost:8787'
  return `// Generated by IntentStack. Regenerate with: intentstack testgen --project <dir> --out tests/generated
import test from 'node:test'
import assert from 'node:assert/strict'

const BASE_URL = process.env.INTENTSTACK_BASE_URL || ${JSON.stringify(defaultBaseUrl)}
const AUTH_TOKEN = process.env.INTENTSTACK_AUTH_TOKEN || ''
const CSRF_TOKEN = process.env.INTENTSTACK_CSRF_TOKEN || ''
const TENANT_ID = process.env.INTENTSTACK_TEST_TENANT_ID || ''
const RUN_MUTATIONS = process.env.INTENTSTACK_RUN_MUTATION_TESTS === 'true'
const OPERATIONS = ${JSON.stringify(operations, null, 2)}

function headers(op) {
  const out = { Accept: 'application/json' }
  if (AUTH_TOKEN) out.Authorization = \`Bearer \${AUTH_TOKEN}\`
  if (op.body) out['Content-Type'] = 'application/json'
  if (op.mutation && CSRF_TOKEN) out['X-CSRF-Token'] = CSRF_TOKEN
  if (op.tenancy && TENANT_ID) out[op.tenantHeader] = TENANT_ID
  return out
}

function operationUrl(op) {
  const id = process.env[op.idEnv] || process.env.INTENTSTACK_TEST_RECORD_ID || ''
  const url = new URL(op.path.replace('{id}', encodeURIComponent(id)), BASE_URL)
  if (op.tenancy && op.stream && TENANT_ID) url.searchParams.set('tenant_id', TENANT_ID)
  return url.toString()
}

function skipReason(op) {
  if (op.mutation && !RUN_MUTATIONS) return 'set INTENTSTACK_RUN_MUTATION_TESTS=true to run mutating contract tests'
  if (op.tenancy && !TENANT_ID) return 'set INTENTSTACK_TEST_TENANT_ID'
  if (op.path.includes('{id}') && !(process.env[op.idEnv] || process.env.INTENTSTACK_TEST_RECORD_ID)) return \`set \${op.idEnv} or INTENTSTACK_TEST_RECORD_ID\`
  return null
}

function assertStatus(op, res) {
  assert.notEqual(res.status, 404, \`\${op.method} \${op.path} is not mounted\`)
  assert.notEqual(res.status, 405, \`\${op.method} \${op.path} method is not allowed\`)
  if (op.auth && [401, 403].includes(res.status)) return
  assert.ok(op.expected.includes(res.status), \`\${op.method} \${op.path} returned \${res.status}, expected \${op.expected.join(', ')}\`)
}

for (const op of OPERATIONS) {
  const skip = skipReason(op)
  test(\`\${op.method} \${op.path} - \${op.action}\`, skip ? { skip } : {}, async () => {
    const res = await fetch(operationUrl(op), {
      method: op.method,
      headers: headers(op),
      body: op.body ? JSON.stringify(op.body) : undefined,
    })
    assertStatus(op, res)
  })
}
`
}

function testReadme(graph, operations) {
  const defaultBaseUrl = graph.project?.target === 'next_shadcn' ? 'http://localhost:3000' : 'http://localhost:8787'
  const mutationCount = operations.filter((op) => op.mutation).length
  const hasTenancy = operations.some((op) => op.tenancy)
  return `# Generated IntentStack Tests

Generated from intent project \`${graph.project?.id || 'app'}\`.

Run against a running generated app:

\`\`\`bash
INTENTSTACK_BASE_URL=${defaultBaseUrl} node --test tests/generated/api-contract.test.mjs
\`\`\`

Protected endpoints accept \`INTENTSTACK_AUTH_TOKEN\`. Cookie-auth CSRF flows can pass
\`INTENTSTACK_CSRF_TOKEN\`.
${hasTenancy ? `
Multi-tenant endpoints require \`INTENTSTACK_TEST_TENANT_ID\`.
` : ''}

Mutating tests are skipped by default. To run them:

\`\`\`bash
INTENTSTACK_RUN_MUTATION_TESTS=true node --test tests/generated/api-contract.test.mjs
\`\`\`

Operations generated: ${operations.length}. Mutating operations: ${mutationCount}.
`
}

function samplePayload(entity, opts = {}) {
  const out = {}
  for (const field of entity.fields || []) {
    if (opts.partial && field.required !== true) continue
    out[field.id] = sampleValue(field)
  }
  return out
}

function sampleValue(field) {
  if (field.type === 'number') return 1
  if (field.type === 'boolean') return true
  if (field.type === 'datetime') return '2026-01-01T00:00:00.000Z'
  if (field.type === 'enum') return field.values?.[0] || 'new'
  if (field.type === 'text') return `Generated ${field.label || field.id}`
  return `Generated ${field.label || field.id}`
}

function envName(value) {
  return String(value || 'record').replace(/[^a-z0-9]+/gi, '_').replace(/^_|_$/g, '').toUpperCase() || 'RECORD'
}
