/**
 * @generated by IntentStack (target: web_ts_minimal). DO NOT EDIT BY HAND.
 * Source of truth: intent/app.intent.yaml — re-run `intentstack build` to regenerate.
 */
import { Routes, Route } from 'react-router-dom'
import { HomePage } from './generated/pages/HomePage'
import { DashboardLeadsPage } from './generated/pages/DashboardLeadsPage'
import { DashboardLeadDetailPage } from './generated/pages/DashboardLeadDetailPage'

export function AppRoutes() {
  return (
    <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/dashboard/leads" element={<DashboardLeadsPage />} />
        <Route path="/dashboard/leads/:id" element={<DashboardLeadDetailPage />} />
    </Routes>
  )
}
