// Project scaffolding: package.json, tsconfig, vite/tailwind/postcss config, env, README.
// These are pinned, conventional config files for the web_ts_minimal target.
import { dbDriver } from './shared/db_driver.js'
import { declaredUsers, hasActionAuth, hasPageAuth } from './shared/modules.js'

export function emitProject(graph) {
  const id = (graph.project?.id || 'app').toLowerCase().replace(/[^a-z0-9-]/g, '-')
  const name = graph.project?.name || 'IntentStack App'
  const useAuth = hasActionAuth(graph.actions) || hasPageAuth(graph)
  const driver = dbDriver(graph)
  return {
    'package.json': packageJson(id, { useAuth, driver }),
    'tsconfig.json': tsconfig(),
    'vite.config.ts': viteConfig(),
    'tailwind.config.js': tailwindConfig(),
    'postcss.config.js': postcssConfig(),
    '.gitignore': gitignore(driver),
    '.env.example': envExample(graph, { useAuth, driver }),
    'README.md': appReadme(name, driver),
  }
}

function packageJson(id, opts = {}) {
  const authDeps = opts.useAuth ? { bcryptjs: '^2.4.3' } : {}
  const authDevDeps = opts.useAuth ? { '@types/bcryptjs': '^2.4.6' } : {}
  return JSON.stringify({
    name: `${id}-generated`,
    private: true,
    type: 'module',
    scripts: {
      dev: 'concurrently -k -n web,api -c blue,green "vite" "tsx watch server/index.ts"',
      'dev:web': 'vite',
      'dev:api': 'tsx watch server/index.ts',
      build: 'vite build',
      start: 'tsx server/index.ts',
      migrate: 'tsx server/generated/db/migrate.ts',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      '@hono/node-server': '^1.13.7',
      hono: '^4.6.14',
      react: '^18.3.1',
      'react-dom': '^18.3.1',
      'react-router-dom': '^6.28.0',
      zod: '^3.23.8',
      ...opts.driver.packageDependencies,
      ...authDeps,
    },
    devDependencies: {
      '@types/node': '^22.10.1',
      '@types/react': '^18.3.12',
      '@types/react-dom': '^18.3.1',
      ...authDevDeps,
      '@vitejs/plugin-react': '^4.3.4',
      autoprefixer: '^10.4.20',
      concurrently: '^9.1.0',
      daisyui: '^4.12.14',
      postcss: '^8.4.49',
      prettier: '^3.4.2',
      tailwindcss: '^3.4.15',
      tsx: '^4.19.2',
      typescript: '^5.7.2',
      vite: '^5.4.11',
    },
  }, null, 2) + '\n'
}

function tsconfig() {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      module: 'ESNext',
      moduleResolution: 'bundler',
      lib: ['ES2022', 'DOM', 'DOM.Iterable'],
      jsx: 'react-jsx',
      strict: true,
      skipLibCheck: true,
      noEmit: true,
      esModuleInterop: true,
      resolveJsonModule: true,
      types: ['vite/client', 'node'],
    },
    include: ['src', 'server'],
  }, null, 2) + '\n'
}

function viteConfig() {
  return `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// During dev, the web app (5173) proxies /api to the Hono server (8787).
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: { '/api': 'http://localhost:8787' },
  },
})
`
}

function tailwindConfig() {
  return `import daisyui from 'daisyui'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: { extend: {} },
  plugins: [daisyui],
  daisyui: { themes: ['light', 'corporate'] },
}
`
}

function postcssConfig() {
  return `export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n}\n`
}

function gitignore(driver) {
  return ['node_modules', 'dist', ...driver.gitignore, '.env'].join('\n') + '\n'
}

function envExample(graph, opts = {}) {
  const lines = [
    'PORT=8787',
    ...opts.driver.envExampleLines(graph),
    '# VITE_API_URL=   # leave empty in dev (vite proxies /api)',
    '',
    '# OpenTelemetry OTLP/HTTP trace export. Leave unset to disable.',
    '# OTEL_SERVICE_NAME=intentstack-generated',
    '# OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318',
    '# OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4318/v1/traces',
    '# OTEL_EXPORTER_OTLP_HEADERS=Authorization=Bearer token',
  ]
  if (opts.useAuth) {
    lines.push(
      '',
      'INTENTSTACK_SESSION_SECRET=replace-with-at-least-32-random-characters',
      'INTENTSTACK_SESSION_TTL_SECONDS=28800',
      '# Store bcrypt hashes in auth password env vars. Use INTENTSTACK_ALLOW_PLAIN_PASSWORDS=true only for local demos.',
    )
    for (const user of declaredUsers(graph)) {
      const envName = passwordEnvName(user.password)
      if (envName) lines.push(`# ${envName}=$2b$12$...`)
    }
  }
  if ((graph.workflows || []).length > 0) {
    lines.push('', '# INTENTSTACK_WORKFLOW_MAX_ATTEMPTS=3')
  }
  return lines.join('\n') + '\n'
}

function passwordEnvName(value) {
  return typeof value === 'string' && value.startsWith('env:') ? value.slice(4) : null
}

function appReadme(name, driver) {
  return `# ${name}

> Generated by **IntentStack** from \`intent/app.intent.yaml\`. Do not edit files under
> \`src/generated/\` or \`server/generated/\` - change the intent and re-run the compiler.

## Run

\`\`\`bash
npm install
npm run dev      # web -> http://localhost:5173   api -> http://localhost:8787
\`\`\`

${driver.readmeDatabase()}
The landing form POSTs to the API; the dashboard reads it back.

## Layout

- \`src/generated/\` - pages + components (managed, regenerated each build)
- \`server/generated/\` - Drizzle schema, zod validators, Hono routes (managed)
- \`src/custom/\`, \`server/custom/\` - your hand-written code (never overwritten)
`
}
