// Shared helpers for the web_ts_minimal emitters.

export const BANNER_TS =
  '/**\n' +
  ' * @generated by IntentStack (target: web_ts_minimal). DO NOT EDIT BY HAND.\n' +
  ' * Source of truth: intent/app.intent.yaml - re-run `intentstack build` to regenerate.\n' +
  ' */\n'

// snake_case -> PascalCase / id -> PascalCase
export function pascal(s) {
  return String(s).replace(/(^|[_\-\s]+)(\w)/g, (_, __, c) => c.toUpperCase())
}

// DB column name: camelCase/PascalCase id -> snake_case
export function snake(s) {
  return String(s).replace(/[A-Z]/g, (m) => '_' + m.toLowerCase()).replace(/^_/, '')
}

// JS string literal (safe for JSX attributes)
export function jsStr(s) { return JSON.stringify(String(s ?? '')) }

// Safe JSX text node: render through an expression container so braces/quotes
// in user content can never break the markup.
export function t(s) { return `{${JSON.stringify(String(s ?? ''))}}` }
