/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core'

export const lead = sqliteTable('leads', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  phone: text('phone').notNull(),
  company: text('company'),
  message: text('message'),
  status: text('status').default('new'),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
})
