// Target adapter: next_shadcn — Next.js App Router + shadcn/ui + route handlers, on the
// SAME Drizzle/SQLite data layer as web_ts_minimal. Same intent, different "how".
import { posix } from 'node:path'
import { pascal, jsStr, t } from '../emit/util.js'
import { schemaImports, schemaBody, migrationSql, validatorBody, entityClientNeeds } from '../emit/shared/datamodel.js'
import { RECORD_ACTIONS } from '../registry.js'
import { hasActionAuth, hasPageAuth, integrationsTs, isActivePolicy, reactAuthTs, requestAuthTs, roleLiteral, workflowsTs } from '../emit/shared/modules.js'

const BANNER = '/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */\n'

export const managedZones = ['app', 'components', 'lib', 'migrations']

export function planFiles(graph) {
  return {
    ...projectFiles(graph),
    ...uiPrimitives(),
    ...dataLayer(graph),
    ...apiRoutes(graph),
    ...frontend(graph),
  }
}

// ---- design tokens --------------------------------------------------------
const RADIUS_REM = { none: '0rem', sm: '0.25rem', md: '0.5rem', lg: '0.75rem', xl: '1rem', full: '9999px' }
const PAD = { compact: 'py-12', comfortable: 'py-20', spacious: 'py-28' }
const radiusVar = (theme) => RADIUS_REM[theme?.radius] || '0.5rem'
const pad = (theme) => PAD[theme?.density] || 'py-20'

// ---- project scaffolding --------------------------------------------------
function projectFiles(graph) {
  const id = (graph.project?.id || 'app').toLowerCase().replace(/[^a-z0-9-]/g, '-')
  const name = graph.project?.name || 'IntentStack App'
  return {
    'package.json': packageJson(id),
    'tsconfig.json': tsconfig(),
    'next.config.mjs': 'const nextConfig = {}\nexport default nextConfig\n',
    'next-env.d.ts': '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// NOTE: This file should not be edited\n// see https://nextjs.org/docs/app/building-your-application/configuring/typescript for more information.\n',
    'postcss.config.mjs': 'export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n}\n',
    'tailwind.config.ts': tailwindConfig(),
    'app/globals.css': globalsCss(graph.theme),
    'components.json': componentsJson(),
    '.gitignore': ['node_modules', '.next', '*.db', 'data.db', '.env'].join('\n') + '\n',
    '.env.example': 'DB_URL=file:./data.db\n',
    'README.md': appReadme(name),
  }
}

function packageJson(id) {
  return JSON.stringify({
    name: `${id}-next`,
    private: true,
    scripts: { dev: 'next dev', build: 'next build', start: 'next start', typecheck: 'tsc --noEmit' },
    dependencies: {
      '@libsql/client': '^0.14.0',
      'class-variance-authority': '^0.7.0',
      clsx: '^2.1.1',
      'drizzle-orm': '^0.36.4',
      next: '^14.2.18',
      react: '^18.3.1',
      'react-dom': '^18.3.1',
      'tailwind-merge': '^2.5.4',
      zod: '^3.23.8',
    },
    devDependencies: {
      '@types/node': '^22.10.1',
      '@types/react': '^18.3.12',
      '@types/react-dom': '^18.3.1',
      autoprefixer: '^10.4.20',
      postcss: '^8.4.49',
      tailwindcss: '^3.4.15',
      typescript: '^5.7.2',
    },
  }, null, 2) + '\n'
}

function tsconfig() {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: false,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2) + '\n'
}

function tailwindConfig() {
  return `import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    container: { center: true, padding: '2rem', screens: { '2xl': '1400px' } },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
      },
      borderRadius: { lg: 'var(--radius)', md: 'calc(var(--radius) - 2px)', sm: 'calc(var(--radius) - 4px)' },
    },
  },
  plugins: [],
}

export default config
`
}

function globalsCss(theme) {
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
    --card: 0 0% 100%;
    --card-foreground: 222.2 84% 4.9%;
    --primary: 222.2 47.4% 11.2%;
    --primary-foreground: 210 40% 98%;
    --secondary: 210 40% 96.1%;
    --secondary-foreground: 222.2 47.4% 11.2%;
    --muted: 210 40% 96.1%;
    --muted-foreground: 215.4 16.3% 46.9%;
    --accent: 210 40% 96.1%;
    --accent-foreground: 222.2 47.4% 11.2%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 40% 98%;
    --border: 214.3 31.8% 91.4%;
    --input: 214.3 31.8% 91.4%;
    --ring: 222.2 84% 4.9%;
    --radius: ${radiusVar(theme)};
  }
  * { @apply border-border; }
  body { @apply bg-background text-foreground; }
}
`
}

function componentsJson() {
  return JSON.stringify({
    $schema: 'https://ui.shadcn.com/schema.json',
    style: 'default',
    rsc: true,
    tsx: true,
    tailwind: { config: 'tailwind.config.ts', css: 'app/globals.css', baseColor: 'slate', cssVariables: true, prefix: '' },
    aliases: { components: '@/components', utils: '@/lib/utils' },
  }, null, 2) + '\n'
}

function appReadme(name) {
  return `# ${name} (Next.js + shadcn/ui)

> Generated by **IntentStack** from the SAME \`intent/app.intent.yaml\` as the
> Vite/daisyUI build — only the target differs. Do not edit \`app/\`, \`components/\`,
> or \`lib/\`; change the intent and re-run the compiler.

\`\`\`bash
npm install
npm run dev     # http://localhost:3000
\`\`\`

The route handler under \`app/api/\` applies \`migrations/0000_init.sql\` to a local SQLite
file on first request. Submit the form on \`/\`, then open \`/dashboard/leads\`.
`
}

// ---- shadcn/ui primitives (what \`npx shadcn add\` would vendor) ------------
function uiPrimitives() {
  return {
    'lib/utils.ts': `import { clsx, type ClassValue } from 'clsx'
import { twMerge } from 'tailwind-merge'

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`,
    'components/ui/button.tsx': `import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const buttonVariants = cva(
  'inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
        outline: 'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost: 'hover:bg-accent hover:text-accent-foreground',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: { default: 'h-10 px-4 py-2', sm: 'h-9 rounded-md px-3', lg: 'h-11 rounded-md px-8', icon: 'h-10 w-10' },
    },
    defaultVariants: { variant: 'default', size: 'default' },
  },
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => (
    <button className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />
  ),
)
Button.displayName = 'Button'

export { Button, buttonVariants }
`,
    'components/ui/input.tsx': `import * as React from 'react'
import { cn } from '@/lib/utils'

const Input = React.forwardRef<HTMLInputElement, React.InputHTMLAttributes<HTMLInputElement>>(
  ({ className, type, ...props }, ref) => (
    <input
      type={type}
      className={cn(
        'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
        className,
      )}
      ref={ref}
      {...props}
    />
  ),
)
Input.displayName = 'Input'

export { Input }
`,
    'components/ui/textarea.tsx': `import * as React from 'react'
import { cn } from '@/lib/utils'

const Textarea = React.forwardRef<HTMLTextAreaElement, React.TextareaHTMLAttributes<HTMLTextAreaElement>>(
  ({ className, ...props }, ref) => (
    <textarea
      className={cn(
        'flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
        className,
      )}
      ref={ref}
      {...props}
    />
  ),
)
Textarea.displayName = 'Textarea'

export { Textarea }
`,
    'components/ui/card.tsx': `import * as React from 'react'
import { cn } from '@/lib/utils'

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('rounded-lg border bg-card text-card-foreground shadow-sm', className)} {...props} />
  ),
)
Card.displayName = 'Card'

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => <div ref={ref} className={cn('flex flex-col space-y-1.5 p-6', className)} {...props} />,
)
CardHeader.displayName = 'CardHeader'

const CardTitle = React.forwardRef<HTMLHeadingElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h3 ref={ref} className={cn('text-lg font-semibold leading-none tracking-tight', className)} {...props} />
  ),
)
CardTitle.displayName = 'CardTitle'

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => <div ref={ref} className={cn('p-6 pt-0', className)} {...props} />,
)
CardContent.displayName = 'CardContent'

export { Card, CardHeader, CardTitle, CardContent }
`,
    'components/ui/table.tsx': `import * as React from 'react'
import { cn } from '@/lib/utils'

const Table = React.forwardRef<HTMLTableElement, React.HTMLAttributes<HTMLTableElement>>(
  ({ className, ...props }, ref) => (
    <div className="relative w-full overflow-auto">
      <table ref={ref} className={cn('w-full caption-bottom text-sm', className)} {...props} />
    </div>
  ),
)
Table.displayName = 'Table'

const TableHeader = React.forwardRef<HTMLTableSectionElement, React.HTMLAttributes<HTMLTableSectionElement>>(
  ({ className, ...props }, ref) => <thead ref={ref} className={cn('[&_tr]:border-b', className)} {...props} />,
)
TableHeader.displayName = 'TableHeader'

const TableBody = React.forwardRef<HTMLTableSectionElement, React.HTMLAttributes<HTMLTableSectionElement>>(
  ({ className, ...props }, ref) => <tbody ref={ref} className={cn('[&_tr:last-child]:border-0', className)} {...props} />,
)
TableBody.displayName = 'TableBody'

const TableRow = React.forwardRef<HTMLTableRowElement, React.HTMLAttributes<HTMLTableRowElement>>(
  ({ className, ...props }, ref) => (
    <tr ref={ref} className={cn('border-b transition-colors hover:bg-muted/50', className)} {...props} />
  ),
)
TableRow.displayName = 'TableRow'

const TableHead = React.forwardRef<HTMLTableCellElement, React.ThHTMLAttributes<HTMLTableCellElement>>(
  ({ className, ...props }, ref) => (
    <th ref={ref} className={cn('h-12 px-4 text-left align-middle font-medium text-muted-foreground', className)} {...props} />
  ),
)
TableHead.displayName = 'TableHead'

const TableCell = React.forwardRef<HTMLTableCellElement, React.TdHTMLAttributes<HTMLTableCellElement>>(
  ({ className, ...props }, ref) => <td ref={ref} className={cn('p-4 align-middle', className)} {...props} />,
)
TableCell.displayName = 'TableCell'

export { Table, TableHeader, TableBody, TableRow, TableHead, TableCell }
`,
  }
}

// ---- data layer (shared content, Next placement) -------------------------
function dataLayer(graph) {
  const files = {}
  files['lib/db/schema.ts'] = BANNER + schemaImports() + schemaBody(graph)
  files['lib/db/client.ts'] = BANNER + `import { drizzle } from 'drizzle-orm/libsql'
import { createClient } from '@libsql/client'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const url = process.env.DB_URL ?? 'file:./data.db'
export const client = createClient({ url })
export const db = drizzle(client)

let migrated: Promise<unknown> | null = null
export function ensureMigrated() {
  if (!migrated) {
    const sql = readFileSync(join(process.cwd(), 'migrations/0000_init.sql'), 'utf8')
    migrated = client.executeMultiple(sql)
  }
  return migrated
}
`
  files['migrations/0000_init.sql'] = migrationSql(graph)
  for (const e of graph.entities) {
    files[`lib/validators/${e.id.toLowerCase()}.ts`] = BANNER + validatorBody(e)
  }
  files['lib/api/client.ts'] = apiClientTs(graph)
  if (hasActionAuth(graph.actions) || hasPageAuth(graph)) files['lib/auth.ts'] = requestAuthTs(graph, BANNER)
  if ((graph.workflows || []).length > 0) files['lib/workflows.ts'] = workflowsTs(graph, BANNER)
  if ((graph.integrations || []).length > 0) files['lib/integrations.ts'] = integrationsTs(graph, BANNER)
  return files
}

function apiClientTs(graph) {
  let out = BANNER
  for (const [eid, types] of Object.entries(entityClientNeeds(graph))) {
    const e = graph.getEntity(eid)
    const base = e?.table || eid.toLowerCase()
    const P = pascal(eid)
    if (types.has('create_record')) {
      out += `export async function create${P}(payload: Record<string, unknown>) {
  const res = await fetch('/api/${base}', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  })
  const json = await res.json().catch(() => ({}))
  return { ok: res.ok, data: json.data, error: json.error }
}

`
    }
    if (types.has('list_records')) {
      out += `export async function list${P}(): Promise<Array<Record<string, unknown>>> {
  const res = await fetch('/api/${base}', { cache: 'no-store' })
  const json = await res.json().catch(() => ({ data: [] }))
  return (json.data ?? []) as Array<Record<string, unknown>>
}

`
    }
    if (types.has('get_record')) {
      out += `export async function get${P}(id: number): Promise<{ ok: boolean; data?: Record<string, unknown>; error?: unknown }> {
  const res = await fetch('/api/${base}/' + id, { cache: 'no-store' })
  const json = await res.json().catch(() => ({}))
  return { ok: res.ok, data: json.data, error: json.error }
}

`
    }
    if (types.has('update_record')) {
      out += `export async function update${P}(id: number, payload: Record<string, unknown>) {
  const res = await fetch('/api/${base}/' + id, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  })
  const json = await res.json().catch(() => ({}))
  return { ok: res.ok, data: json.data, error: json.error }
}

`
    }
    if (types.has('delete_record')) {
      out += `export async function delete${P}(id: number) {
  const res = await fetch('/api/${base}/' + id, { method: 'DELETE' })
  const json = await res.json().catch(() => ({}))
  return { ok: res.ok, data: json.data, error: json.error }
}

`
    }
  }
  return out
}

// ---- API route handlers ---------------------------------------------------
function apiRoutes(graph) {
  const files = {}
  if (hasActionAuth(graph.actions) || hasPageAuth(graph)) {
    files['app/api/auth/login/route.ts'] = BANNER + `import { loginRequest } from '@/lib/auth'

export async function POST(req: Request) {
  return loginRequest(req)
}
`
    files['app/api/auth/logout/route.ts'] = BANNER + `import { logoutRequest } from '@/lib/auth'

export async function POST(req: Request) {
  return logoutRequest(req)
}
`
    files['app/api/auth/me/route.ts'] = BANNER + `import { meRequest } from '@/lib/auth'

export async function GET(req: Request) {
  return meRequest(req)
}
`
  }
  const byEntity = {}
  for (const a of graph.actions) {
    if (!a.entity || !RECORD_ACTIONS.includes(a.type)) continue
    ;(byEntity[a.entity] ||= []).push(a)
  }
  const opts = { useAuth: hasActionAuth(graph.actions), useWorkflows: (graph.workflows || []).length > 0 }
  for (const [eid, actions] of Object.entries(byEntity)) {
    const e = graph.getEntity(eid)
    if (!e) continue
    const tname = e.id.toLowerCase()
    const base = e.table || tname
    const types = new Set(actions.map((a) => a.type))
    files[`app/api/${base}/route.ts`] = collectionRoute(tname, base, types, actions, opts)
    if (types.has('get_record') || types.has('update_record') || types.has('delete_record')) {
      files[`app/api/${base}/[id]/route.ts`] = itemRoute(tname, types, actions, opts)
    }
  }
  return files
}

function collectionRoute(tname, base, types, actions, opts) {
  const action = (type) => actions.find((a) => a.type === type)
  let out = BANNER + `import { db, ensureMigrated } from '@/lib/db/client'
import { ${tname} } from '@/lib/db/schema'
import { desc } from 'drizzle-orm'
import { ${tname}CreateSchema } from '@/lib/validators/${tname}'
${opts.useAuth ? `import { assertRequestRole } from '@/lib/auth'\n` : ''}${opts.useWorkflows ? `import { runWorkflows } from '@/lib/workflows'\n` : ''}
`
  if (types.has('list_records')) out += `
export async function GET(${isActivePolicy(action('list_records')?.auth) ? 'req: Request' : ''}) {
${nextAuthGuard(action('list_records'), 'req')}
  await ensureMigrated()
  const rows = await db.select().from(${tname}).orderBy(desc(${tname}.createdAt))
  return Response.json({ data: rows })
}
`
  if (types.has('create_record')) out += `
export async function POST(req: Request) {
${nextAuthGuard(action('create_record'), 'req')}
  await ensureMigrated()
  const body = await req.json().catch(() => null)
  const parsed = ${tname}CreateSchema.safeParse(body)
  if (!parsed.success) return Response.json({ error: 'validation', details: parsed.error.flatten() }, { status: 400 })
  const result = await db.insert(${tname}).values({ ...parsed.data, createdAt: new Date() }).returning()
${nextWorkflowCall(opts, action('create_record'), 'result[0]')}
  return Response.json({ data: result[0] }, { status: 201 })
}
`
  return out
}

function itemRoute(tname, types, actions, opts) {
  const imports = [
    `import { db, ensureMigrated } from '@/lib/db/client'`,
    `import { ${tname} } from '@/lib/db/schema'`,
    `import { eq } from 'drizzle-orm'`,
  ]
  if (types.has('update_record')) imports.push(`import { ${tname}CreateSchema } from '@/lib/validators/${tname}'`)
  if (opts.useAuth) imports.push(`import { assertRequestRole } from '@/lib/auth'`)
  if (opts.useWorkflows) imports.push(`import { runWorkflows } from '@/lib/workflows'`)
  const action = (type) => actions.find((a) => a.type === type)
  let out = BANNER + imports.join('\n') + `

type Ctx = { params: { id: string } }
`
  if (types.has('get_record')) out += `
export async function GET(_req: Request, { params }: Ctx) {
${nextAuthGuard(action('get_record'), '_req')}
  await ensureMigrated()
  const rows = await db.select().from(${tname}).where(eq(${tname}.id, Number(params.id)))
  if (rows.length === 0) return Response.json({ error: 'not_found' }, { status: 404 })
  return Response.json({ data: rows[0] })
}
`
  if (types.has('update_record')) out += `
export async function PUT(req: Request, { params }: Ctx) {
${nextAuthGuard(action('update_record'), 'req')}
  await ensureMigrated()
  const body = await req.json().catch(() => null)
  const parsed = ${tname}CreateSchema.partial().safeParse(body)
  if (!parsed.success) return Response.json({ error: 'validation', details: parsed.error.flatten() }, { status: 400 })
  const result = await db.update(${tname}).set(parsed.data).where(eq(${tname}.id, Number(params.id))).returning()
  if (result.length === 0) return Response.json({ error: 'not_found' }, { status: 404 })
${nextWorkflowCall(opts, action('update_record'), 'result[0]')}
  return Response.json({ data: result[0] })
}
`
  if (types.has('delete_record')) out += `
export async function DELETE(_req: Request, { params }: Ctx) {
${nextAuthGuard(action('delete_record'), '_req')}
  await ensureMigrated()
  await db.delete(${tname}).where(eq(${tname}.id, Number(params.id)))
${nextWorkflowCall(opts, action('delete_record'), '{ id: Number(params.id) }')}
  return Response.json({ ok: true })
}
`
  return out
}

function nextAuthGuard(action, reqName) {
  if (!action || !isActivePolicy(action.auth)) return ''
  return `  const auth = assertRequestRole(${reqName}, ${roleLiteral(action.auth)})
  if (auth) return auth
`
}

function nextWorkflowCall(opts, action, payloadExpr) {
  if (!opts.useWorkflows || !action) return ''
  return `  await runWorkflows(${JSON.stringify(action.id)}, ${payloadExpr})
`
}

// ---- frontend (pages + section components) --------------------------------
function frontend(graph) {
  const files = {}
  files['app/layout.tsx'] = layoutTsx(graph.project?.name || 'IntentStack App')
  if (hasPageAuth(graph)) files['components/generated/ProtectedPage.tsx'] = reactAuthTs(graph, BANNER)
  const used = new Set()
  const globalNavName = hasGlobalNavigation(graph) ? 'AppNav' : null
  if (globalNavName) {
    used.add(globalNavName)
    files[`components/generated/${globalNavName}.tsx`] = buildNav(globalNavName, {
      id: 'app_nav',
      logo: graph.navigation.logo || graph.project?.name,
      items: graph.navigation.items || [],
    })
  }
  for (const p of graph.pages) {
    const refs = []
    for (const s of p.sections || []) {
      let cname = pascal(s.id)
      if (used.has(cname)) cname = pascal(p.id) + cname
      used.add(cname)
      const content = renderSection(graph, cname, s, p)
      if (!content) continue
      files[`components/generated/${cname}.tsx`] = content
      refs.push(cname)
    }
    files[pageFile(p)] = pageTsx(p, refs, pageUsesGlobalNav(graph, p) ? globalNavName : null)
  }
  return files
}

const pageFile = (p) => 'app' + (p.path && p.path !== '/' ? nextRoutePath(p.path) : '') + '/page.tsx'

function nextRoutePath(path) {
  return String(path).split('/').map((part) => part.startsWith(':') ? `[${part.slice(1)}]` : part).join('/')
}

function layoutTsx(name) {
  return BANNER + `import type { ReactNode } from 'react'
import './globals.css'

export const metadata = { title: ${jsStr(name)} }

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`
}

function pageTsx(p, refs, navName) {
  const imports = [
    navName ? `import { ${navName} } from '@/components/generated/${navName}'` : null,
    ...refs.map((n) => `import { ${n} } from '@/components/generated/${n}'`),
  ].filter(Boolean).join('\n')
  const nav = navName ? `      <${navName} />\n` : ''
  const body = refs.map((n) => `      <${n} />`).join('\n')
  const authImport = isActivePolicy(p.auth) ? `import { ProtectedPage } from '@/components/generated/ProtectedPage'\n` : ''
  const open = isActivePolicy(p.auth) ? `    <ProtectedPage roles={${roleLiteral(p.auth)}}>\n` : ''
  const close = isActivePolicy(p.auth) ? `    </ProtectedPage>\n` : ''
  if (p.layout === 'dashboard') {
    return BANNER + `${imports}
${authImport}

export default function Page() {
  return (
${open}    <main className="min-h-screen bg-muted/20">
${nav}
      <header className="mx-auto max-w-6xl px-4 pt-10"><h1 className="text-2xl font-semibold">${t(p.title || pascal(p.id))}</h1></header>
${body}
    </main>
${close}  )
}
`
  }
  return BANNER + `${imports}
${authImport}

export default function Page() {
  return (
${open}    <main className="min-h-screen bg-background">
${nav}${body}
    </main>
${close}  )
}
`
}

function hasGlobalNavigation(graph) {
  return Boolean(graph.navigation && graph.navigation.enabled !== false)
}

function pageUsesGlobalNav(graph, page) {
  return hasGlobalNavigation(graph) && page.navigation !== false
}

function renderSection(graph, name, s, page) {
  switch (s.type) {
    case 'navbar': return buildNav(name, s)
    case 'hero': return buildHero(name, s, graph.theme)
    case 'card_grid': return buildFeatures(name, s, graph.theme)
    case 'pricing_cards': return buildPricingCards(name, s, graph.theme)
    case 'stats': return buildStats(name, s, graph.theme)
    case 'content': return buildContent(name, s, graph.theme, page)
    case 'custom_component': return buildCustomComponent(name, s, 'components/generated')
    case 'form': return buildForm(name, graph, s, graph.theme)
    case 'table': return buildTable(name, graph, s, page)
    case 'record_detail': return buildRecordDetail(name, graph, s, page, graph.theme)
    case 'footer': return buildFooter(name, s)
    default: return null
  }
}

function buildNav(name, s) {
  const items = (s.items || [])
    .map((it) => `          <a href=${jsStr(it.href || '#')} className="transition-colors hover:text-foreground">${t(it.label)}</a>`)
    .join('\n')
  return BANNER + `export function ${name}() {
  return (
    <header className="sticky top-0 z-20 border-b bg-background/80 backdrop-blur">
      <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4">
        <span className="text-lg font-semibold">${t(s.logo || 'App')}</span>
        <nav className="flex gap-6 text-sm text-muted-foreground">
${items}
        </nav>
      </div>
    </header>
  )
}
`
}

function buildHero(name, s, theme) {
  const actions = (s.actions || []).map((a) => {
    const variant = a.kind === 'secondary' ? 'secondary' : a.kind === 'outline' ? 'outline' : 'default'
    const href = a.target || a.href || '#'
    return `          <a href=${jsStr(href)} className={cn(buttonVariants({ variant: '${variant}', size: 'lg' }))}>${t(a.label)}</a>`
  }).join('\n')
  return BANNER + `import { buttonVariants } from '@/components/ui/button'
import { cn } from '@/lib/utils'

export function ${name}() {
  return (
    <section className="${pad(theme)} text-center">
      <div className="mx-auto max-w-3xl px-4">
        <h1 className="text-5xl font-bold tracking-tight">${t(s.title)}</h1>
        <p className="mt-6 text-lg text-muted-foreground">${t(s.subtitle)}</p>
        <div className="mt-8 flex flex-wrap justify-center gap-3">
${actions}
        </div>
      </div>
    </section>
  )
}
`
}

function buildFeatures(name, s, theme) {
  const cols = Math.min(Math.max(Number(s.columns) || 3, 1), 4)
  const colClass = { 1: 'md:grid-cols-1', 2: 'md:grid-cols-2', 3: 'md:grid-cols-3', 4: 'md:grid-cols-4' }[cols]
  const cards = (s.items || []).map((it) =>
`          <Card>
            <CardHeader><CardTitle>${t(it.title)}</CardTitle></CardHeader>
            <CardContent className="text-muted-foreground">${t(it.text)}</CardContent>
          </Card>`).join('\n')
  const heading = s.title ? `        <h2 className="mb-10 text-center text-3xl font-semibold">${t(s.title)}</h2>\n` : ''
  return BANNER + `import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'

export function ${name}() {
  return (
    <section id=${jsStr(s.id)} className="${pad(theme)} bg-muted/30">
      <div className="mx-auto max-w-6xl px-4">
${heading}        <div className="grid grid-cols-1 ${colClass} gap-6">
${cards}
        </div>
      </div>
    </section>
  )
}
`
}

function importPath(fromDir, source) {
  const noExt = String(source).replace(/\.(tsx|ts|jsx|js)$/, '')
  let rel = posix.relative(fromDir, noExt)
  if (!rel.startsWith('.')) rel = './' + rel
  return rel
}

function buildCustomComponent(name, s, fromDir) {
  const props = s.props ? `const props = ${JSON.stringify(s.props, null, 2)} as const\n\n` : ''
  const spread = s.props ? ' {...props}' : ''
  return BANNER + `import { ${s.component} } from ${jsStr(importPath(fromDir, s.source))}

${props}export function ${name}() {
  return <${s.component}${spread} />
}
`
}

function buildStats(name, s, theme) {
  const items = (s.items || s.stats || []).map((it) =>
`          <Card>
            <CardHeader><CardTitle>${t(it.value)}</CardTitle></CardHeader>
            <CardContent className="text-muted-foreground">${t(it.label || it.title || it.text)}</CardContent>
          </Card>`).join('\n')
  const heading = s.title ? `        <h2 className="mb-10 text-center text-3xl font-semibold">${t(s.title)}</h2>\n` : ''
  return BANNER + `import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'

export function ${name}() {
  return (
    <section id=${jsStr(s.id)} className="${pad(theme)}">
      <div className="mx-auto max-w-6xl px-4">
${heading}        <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
${items}
        </div>
      </div>
    </section>
  )
}
`
}

function buildPricingCards(name, s, theme) {
  const cols = Math.min(Math.max(Number(s.columns) || 3, 1), 4)
  const colClass = { 1: 'md:grid-cols-1', 2: 'md:grid-cols-2', 3: 'md:grid-cols-3', 4: 'md:grid-cols-4' }[cols]
  const cards = (s.plans || s.items || []).map((it) => {
    const features = (it.features || []).map((f) => `              <li>${t(f)}</li>`).join('\n')
    return `          <Card>
            <CardHeader>
              <CardTitle>${t(it.title || it.name)}</CardTitle>
              <p className="text-3xl font-bold">${t(it.price || it.value || '')}</p>
            </CardHeader>
            <CardContent className="space-y-4 text-muted-foreground">
              ${it.text ? `<p>${t(it.text)}</p>` : ''}
              <ul className="list-disc pl-5 text-sm">
${features}
              </ul>
            </CardContent>
          </Card>`
  }).join('\n')
  const heading = s.title ? `        <h2 className="mb-10 text-center text-3xl font-semibold">${t(s.title)}</h2>\n` : ''
  return BANNER + `import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'

export function ${name}() {
  return (
    <section id=${jsStr(s.id)} className="${pad(theme)} bg-muted/30">
      <div className="mx-auto max-w-6xl px-4">
${heading}        <div className="grid grid-cols-1 ${colClass} gap-6">
${cards}
        </div>
      </div>
    </section>
  )
}
`
}

function buildContent(name, s, theme, page) {
  const headings = (s.blocks || [])
    .filter((block) => block.type === 'heading' && block.text)
    .map((block) => ({ id: block.id || slug(block.text), text: block.text, level: Number(block.level) || 2 }))
  const showToc = s.toc !== false && headings.length > 1
  const blocks = (s.blocks || []).map((block) => renderContentBlock(block)).join('\n')
  const title = s.title ? `          <h1 className="text-4xl font-bold tracking-tight">${t(s.title)}</h1>\n` : ''
  const toc = showToc ? `        <aside className="hidden lg:block">
          <nav className="sticky top-24 rounded-lg border bg-card p-4 text-sm">
            <p className="mb-3 font-medium text-muted-foreground">On this page</p>
${headings.map((h) => `            <a className="${h.level > 2 ? 'ml-3 ' : ''}block py-1 text-muted-foreground transition-colors hover:text-foreground" href="#${slug(h.id)}">${t(h.text)}</a>`).join('\n')}
          </nav>
        </aside>
` : ''
  const grid = showToc ? 'grid gap-10 lg:grid-cols-[220px_minmax(0,1fr)]' : 'grid'
  const max = page?.layout === 'docs' ? 'max-w-6xl' : 'max-w-4xl'
  return BANNER + `export function ${name}() {
  return (
    <section id=${jsStr(s.id)} className="${pad(theme)}">
      <div className="${max} mx-auto px-4 ${grid}">
${toc}        <article className="space-y-6">
${title}${blocks}
        </article>
      </div>
    </section>
  )
}
`
}

function renderContentBlock(block) {
  if (block.type === 'heading') {
    const level = Math.min(Math.max(Number(block.level) || 2, 2), 4)
    const id = slug(block.id || block.text || '')
    const cls = level === 2 ? 'pt-4 text-2xl font-semibold tracking-tight' : level === 3 ? 'pt-3 text-xl font-semibold' : 'pt-2 text-lg font-semibold'
    const Tag = `h${level}`
    return `          <${Tag} id=${jsStr(id)} className="${cls}">${t(block.text)}</${Tag}>`
  }
  if (block.type === 'list') {
    const items = (block.items || []).map((item) => `            <li>${t(item)}</li>`).join('\n')
    return `          <ul className="list-disc space-y-2 pl-6 text-muted-foreground">
${items}
          </ul>`
  }
  if (block.type === 'code') {
    const label = block.language ? `          <div className="text-xs uppercase tracking-wide text-muted-foreground">${t(block.language)}</div>\n` : ''
    return `${label}          <pre className="overflow-x-auto rounded-lg border bg-muted p-4 text-sm"><code>${t(block.code)}</code></pre>`
  }
  if (block.type === 'link') {
    return `          <p><a href=${jsStr(block.href)} className="font-medium text-primary underline-offset-4 hover:underline">${t(block.text)}</a></p>`
  }
  if (block.type === 'callout') {
    const title = block.title ? `            <p className="font-semibold">${t(block.title)}</p>\n` : ''
    return `          <div className="rounded-lg border bg-muted/50 p-4">
${title}            <p className="leading-7 text-muted-foreground">${t(block.text)}</p>
          </div>`
  }
  if (block.type === 'table') {
    const columns = block.columns || []
    const head = columns.map((column) => `              <th className="px-4 py-3 text-left font-medium">${t(column)}</th>`).join('\n')
    const rows = (block.rows || []).map((row) => `            <tr className="border-t">
${columns.map((column, index) => `              <td className="px-4 py-3">${t(tableCell(row, column, index))}</td>`).join('\n')}
            </tr>`).join('\n')
    return `          <div className="overflow-x-auto rounded-lg border">
            <table className="w-full text-sm">
              <thead className="bg-muted/50">
                <tr>
${head}
                </tr>
              </thead>
              <tbody>
${rows}
              </tbody>
            </table>
          </div>`
  }
  return `          <p className="text-base leading-7 text-muted-foreground">${t(block.text)}</p>`
}

function tableCell(row, column, index) {
  if (Array.isArray(row)) return row[index]
  if (row && typeof row === 'object') return row[column] ?? row[slug(column)] ?? ''
  return ''
}

function buildForm(name, graph, s, theme) {
  const entity = graph.getEntity(s.entity)
  const P = pascal(s.entity)
  const fieldRefs = (s.fields && s.fields.length) ? s.fields : (entity?.fields || []).map((f) => f.id)
  const inputs = fieldRefs.map((ref) => {
    const fid = typeof ref === 'string' ? ref : (ref.name || ref.id)
    const f = (entity?.fields || []).find((x) => x.id === fid) || { id: fid, type: 'string' }
    const label = f.label || pascal(fid)
    const req = f.required ? ' required' : ''
    if (f.type === 'text') return `          <Textarea name=${jsStr(fid)}${req} placeholder=${jsStr(label)} />`
    if (f.type === 'enum') {
      const opts = (f.values || []).map((v) => `            <option value=${jsStr(v)}>${t(v)}</option>`).join('\n')
      return `          <select name=${jsStr(fid)}${req} defaultValue="" className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm">
            <option value="" disabled>${t(label)}</option>
${opts}
          </select>`
    }
    if (f.type === 'boolean') return `          <label className="flex items-center gap-2 text-sm"><input type="checkbox" name=${jsStr(fid)} className="h-4 w-4" /><span>${t(label)}</span></label>`
    const inputType = f.type === 'number' ? 'number' : 'text'
    return `          <Input type="${inputType}" name=${jsStr(fid)}${req} placeholder=${jsStr(label)} />`
  }).join('\n')
  const success = s.submit?.success_message || 'Thank you. We will be in touch.'
  return BANNER + `'use client'
import { useState } from 'react'
import type { FormEvent } from 'react'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Button } from '@/components/ui/button'
import { create${P} } from '@/lib/api/client'

export function ${name}() {
  const [status, setStatus] = useState<'idle' | 'loading' | 'ok' | 'error'>('idle')
  async function onSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()
    const form = e.currentTarget
    setStatus('loading')
    const payload = Object.fromEntries(new FormData(form).entries())
    const res = await create${P}(payload)
    setStatus(res.ok ? 'ok' : 'error')
    if (res.ok) form.reset()
  }
  return (
    <section id=${jsStr(s.id)} className="${pad(theme)}">
      <div className="mx-auto max-w-xl px-4">
        <h2 className="mb-8 text-center text-3xl font-semibold">${t(s.title || 'Contact')}</h2>
        <form onSubmit={onSubmit} className="flex flex-col gap-3 rounded-lg border bg-card p-6 shadow-sm">
${inputs}
          <Button type="submit" disabled={status === 'loading'}>{status === 'loading' ? 'Sending…' : 'Submit'}</Button>
          {status === 'ok' && <p className="text-center text-sm text-green-600">${t(success)}</p>}
          {status === 'error' && <p className="text-center text-sm text-destructive">Something went wrong. Please try again.</p>}
        </form>
      </div>
    </section>
  )
}
`
}

function buildTable(name, graph, s, page) {
  const entity = graph.getEntity(s.entity)
  const P = pascal(s.entity)
  const detailAction = (s.row_actions || []).find((a) => (a.type || a) === 'detail')
  const hasDetail = Boolean(detailAction)
  const hasEdit = (s.row_actions || []).some((a) => a.type === 'edit') &&
    graph.actions.some((a) => a.entity === s.entity && a.type === 'update_record')
  const hasDelete = (s.row_actions || []).some((a) => a.type === 'delete') &&
    graph.actions.some((a) => a.entity === s.entity && a.type === 'delete_record')
  const hasActions = hasDetail || hasEdit || hasDelete
  const cols = (s.columns && s.columns.length ? s.columns : (entity?.fields || []).map((f) => f.id))
    .map((c) => (typeof c === 'string' ? c : c.id))
  const ths = cols.map((c) => {
    const f = (entity?.fields || []).find((x) => x.id === c)
    return `                <TableHead>${t(f?.label || pascal(c))}</TableHead>`
  }).join('\n')
  const tds = cols.map((c) => hasEdit
    ? `                  <TableCell>{editingId === Number(row.id) ? <input className="h-8 w-full rounded-md border px-2 text-sm" value={String(draft[${jsStr(c)}] ?? '')} onChange={(e) => setDraftValue(${jsStr(c)}, e.currentTarget.value)} /> : String(row[${jsStr(c)}] ?? '')}</TableCell>`
    : `                  <TableCell>{String(row[${jsStr(c)}] ?? '')}</TableCell>`).join('\n')
  const actionsTh = hasActions ? `                <TableHead className="w-40">Actions</TableHead>\n` : ''
  const detailTarget = (typeof detailAction === 'object' && detailAction.target) || defaultDetailPath(page?.path)
  const detailButton = hasDetail ? `<a className="text-sm text-muted-foreground" href={detailHref(${jsStr(detailTarget)}, row.id)}>Open</a>` : ''
  const editButtons = hasEdit ? `{editingId === Number(row.id) ? (
                      <>
                        <button type="button" className="text-sm font-medium" onClick={saveEdit}>Save</button>
                        <button type="button" className="text-sm text-muted-foreground" onClick={cancelEdit}>Cancel</button>
                      </>
                    ) : (
                      <button type="button" className="text-sm text-muted-foreground" onClick={() => startEdit(row)}>Edit</button>
                    )}` : ''
  const deleteButton = hasDelete ? `<button type="button" className="text-sm text-destructive" onClick={() => onDelete(Number(row.id))}>Delete</button>` : ''
  const actionsTd = hasActions ? `
                  <TableCell>
                    <div className="flex flex-wrap gap-3">
                      ${detailButton}
                      ${editButtons}
                      ${deleteButton}
                    </div>
                  </TableCell>` : ''
  const importNames = [`list${P}`, hasEdit ? `update${P}` : null, hasDelete ? `delete${P}` : null].filter(Boolean).join(', ')
  const colSpan = cols.length + (hasActions ? 1 : 0)
  return BANNER + `'use client'
import { useEffect, useState } from 'react'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { ${importNames} } from '@/lib/api/client'

export function ${name}() {
  const [rows, setRows] = useState<Array<Record<string, unknown>>>([])
  const [loading, setLoading] = useState(true)
  ${hasEdit ? `const [editingId, setEditingId] = useState<number | null>(null)
  const [draft, setDraft] = useState<Record<string, unknown>>({})` : ''}
  async function loadRows() {
    setLoading(true)
    const nextRows = await list${P}()
    setRows(nextRows)
    setLoading(false)
  }
  ${hasEdit ? `function startEdit(row: Record<string, unknown>) {
    setEditingId(Number(row.id))
    setDraft(row)
  }
  function cancelEdit() {
    setEditingId(null)
    setDraft({})
  }
  function setDraftValue(key: string, value: unknown) {
    setDraft((current) => ({ ...current, [key]: value }))
  }
  async function saveEdit() {
    if (editingId == null) return
    const res = await update${P}(editingId, draft)
    if (res.ok) {
      cancelEdit()
      await loadRows()
    }
  }` : ''}
  ${hasDelete ? `async function onDelete(id: number) {
    if (!Number.isFinite(id)) return
    const res = await delete${P}(id)
    if (res.ok) await loadRows()
  }` : ''}
  ${hasDetail ? `function detailHref(pattern: string, id: unknown) {
    return pattern.replace(':id', encodeURIComponent(String(id)))
  }` : ''}
  useEffect(() => { void loadRows() }, [])
  return (
    <div className="mx-auto max-w-6xl px-4 py-6">
      <div className="rounded-lg border">
        <Table>
          <TableHeader>
            <TableRow>
${ths}
${actionsTh}            </TableRow>
          </TableHeader>
          <TableBody>
            {loading && (
              <TableRow><TableCell colSpan={${colSpan}} className="text-center text-muted-foreground">Loading…</TableCell></TableRow>
            )}
            {!loading && rows.length === 0 && (
              <TableRow><TableCell colSpan={${colSpan}} className="text-center text-muted-foreground">No records yet</TableCell></TableRow>
            )}
            {!loading && rows.map((row, i) => (
              <TableRow key={i}>
${tds}
${actionsTd}
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
`
}

function buildRecordDetail(name, graph, s, page, theme) {
  const entity = graph.getEntity(s.entity)
  const P = pascal(s.entity)
  const param = routeParam(page?.path)
  const hasUpdate = Boolean(s.update?.action) &&
    graph.actions.some((a) => a.entity === s.entity && a.type === 'update_record')
  const fieldRefs = (s.fields && s.fields.length) ? s.fields : (entity?.fields || []).map((f) => f.id)
  const fields = fieldRefs.map((ref) => {
    const fid = typeof ref === 'string' ? ref : (ref.name || ref.id)
    const f = (entity?.fields || []).find((x) => x.id === fid)
    const label = f?.label || pascal(fid)
    return hasUpdate ? `          <label className="grid gap-2">
            <span className="text-sm font-medium">${t(label)}</span>
            <Input value={String(draft[${jsStr(fid)}] ?? '')} onChange={(e) => setDraftValue(${jsStr(fid)}, e.currentTarget.value)} />
          </label>` : `          <div>
            <div className="text-sm text-muted-foreground">${t(label)}</div>
            <div className="font-medium">{String(record?.[${jsStr(fid)}] ?? '')}</div>
          </div>`
  }).join('\n')
  const imports = hasUpdate ? `get${P}, update${P}` : `get${P}`
  const uiImports = hasUpdate
    ? `import { Input } from '@/components/ui/input'\nimport { Button } from '@/components/ui/button'\n`
    : ''
  const save = hasUpdate ? `
  function setDraftValue(key: string, value: unknown) {
    setDraft((current) => ({ ...current, [key]: value }))
  }
  async function saveRecord() {
    if (!Number.isFinite(recordId)) return
    setStatus('loading')
    const res = await update${P}(recordId, draft)
    setStatus(res.ok ? 'ok' : 'error')
    if (res.ok) {
      setRecord(res.data ?? draft)
      setDraft(res.data ?? draft)
    }
  }` : ''
  const button = hasUpdate ? `          <Button type="button" onClick={saveRecord} disabled={status === 'loading'}>{status === 'loading' ? 'Saving...' : 'Save changes'}</Button>
          {status === 'ok' && <p className="text-sm text-green-600">Saved.</p>}
          {status === 'error' && <p className="text-sm text-destructive">Could not save changes.</p>}` : ''
  return BANNER + `'use client'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
${uiImports}import { ${imports} } from '@/lib/api/client'

export function ${name}() {
  const params = useParams()
  const rawId = params[${jsStr(param)}]
  const recordId = Number(Array.isArray(rawId) ? rawId[0] : rawId)
  const [record, setRecord] = useState<Record<string, unknown> | null>(null)
  const [draft, setDraft] = useState<Record<string, unknown>>({})
  const [status, setStatus] = useState<'idle' | 'loading' | 'ok' | 'error'>('idle')
  async function loadRecord() {
    if (!Number.isFinite(recordId)) {
      setStatus('error')
      return
    }
    setStatus('loading')
    const res = await get${P}(recordId)
    setStatus(res.ok ? 'idle' : 'error')
    setRecord(res.data ?? null)
    setDraft(res.data ?? {})
  }
${save}
  useEffect(() => { void loadRecord() }, [rawId])
  return (
    <section className="${pad(theme)}">
      <div className="mx-auto max-w-2xl px-4">
        <Card>
          <CardHeader><CardTitle>${t(s.title || entity?.id || 'Record')}</CardTitle></CardHeader>
          <CardContent className="grid gap-4">
            {status === 'loading' && !record && <p className="text-sm text-muted-foreground">Loading...</p>}
${fields}
${button}
          </CardContent>
        </Card>
      </div>
    </section>
  )
}
`
}

function routeParam(path) {
  const part = String(path || '').split('/').find((x) => x.startsWith(':'))
  return part ? part.slice(1) : 'id'
}

function defaultDetailPath(path) {
  const base = String(path || '').replace(/\/$/, '')
  return `${base || '/'}/:id`.replace('//:id', '/:id')
}

function slug(value) {
  return String(value || 'section')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'section'
}

function buildFooter(name, s) {
  return BANNER + `export function ${name}() {
  return (
    <footer className="border-t bg-muted/30 py-8 text-center text-sm text-muted-foreground">
      <p>${t(s.text || '© ' + new Date().getFullYear())}</p>
    </footer>
  )
}
`
}
