const RUST_EMIT_BANNER: &str = "// @generated by IntentStack Rust core. Do not edit by hand.\n\n";

fn emit_file_content(graph: &AppGraph, file: &PlannedFile) -> String {
    match graph.project.target.as_str() {
        "web_ts_minimal" => emit_web_file(graph, file),
        "next_shadcn" => emit_next_file(graph, file),
        _ => format!(
            "{RUST_EMIT_BANNER}// Unsupported target {}\n",
            graph.project.target
        ),
    }
}

fn emit_web_file(graph: &AppGraph, file: &PlannedFile) -> String {
    let path = file.path.as_str();
    match path {
        "package.json" => web_package_json(graph),
        "tsconfig.json" => web_tsconfig(),
        "vite.config.ts" => format!("{RUST_EMIT_BANNER}import {{ defineConfig }} from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({{ plugins: [react()] }})\n"),
        "tailwind.config.js" => "export default { content: ['./index.html', './src/**/*.{ts,tsx}'], theme: { extend: {} }, plugins: [] }\n".to_string(),
        "postcss.config.js" => "export default { plugins: {} }\n".to_string(),
        ".gitignore" => "node_modules\ndist\n.env\n*.db\ndata.db\n".to_string(),
        ".env.example" => "DB_URL=file:./data.db\nINTENTSTACK_AUTO_MIGRATE=false\n".to_string(),
        "README.md" => generated_readme(graph, "Vite React + Hono"),
        "index.html" => "<!doctype html><html><head><meta charset=\"UTF-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" /><title>IntentStack</title></head><body><div id=\"root\"></div><script type=\"module\" src=\"/src/main.tsx\"></script></body></html>\n".to_string(),
        "src/main.tsx" => format!("{RUST_EMIT_BANNER}import React from 'react'\nimport {{ createRoot }} from 'react-dom/client'\nimport {{ App }} from './routes'\n\ncreateRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)\n"),
        "src/routes.tsx" => web_routes_tsx(graph),
        "src/generated/ErrorBoundary.tsx" => format!("{RUST_EMIT_BANNER}import type {{ ReactNode }} from 'react'\n\nexport function ErrorBoundary(props: {{ children: ReactNode }}) {{\n  return <>{{props.children}}</>\n}}\n"),
        "src/generated/api/client.ts" => api_client_ts(),
        "src/generated/auth.ts" => format!("{RUST_EMIT_BANNER}export function useIntentStackRole() {{ return '' }}\nexport function ProtectedPage<T>(props: {{ children: T }}) {{ return props.children }}\n"),
        "server/index.ts" => web_server_index(graph),
        "server/generated/otel.ts" => format!("{RUST_EMIT_BANNER}export function nowNanos() {{ return String(Date.now() * 1000000) }}\nexport async function exportSpan(_span: unknown) {{}}\n"),
        "server/generated/db/schema.ts" => db_schema_ts(graph),
        "server/generated/db/client.ts" => db_client_ts(),
        "server/generated/db/migrate.ts" => format!("{RUST_EMIT_BANNER}import {{ runIntentStackMigrations }} from './client'\n\nawait runIntentStackMigrations()\n"),
        "migrations/0000_init.sql" => migration_sql(graph),
        "migrations/manifest.json" => migration_manifest_json(graph),
        _ if path.starts_with("src/generated/pages/") => web_page_tsx(graph, path),
        _ if path.starts_with("src/generated/components/") => web_component_file(graph, path),
        _ if path.starts_with("server/generated/validators/") => validator_ts(graph, path),
        _ if path.starts_with("server/generated/routes/") => hono_route_ts(graph, path),
        _ if path.starts_with("server/generated/realtime/") => realtime_ts(graph, path),
        _ if path == "server/generated/auth.ts" => format!("{RUST_EMIT_BANNER}export function assertRole() {{}}\n"),
        _ if path == "server/generated/workflows.ts" => format!("{RUST_EMIT_BANNER}export async function dispatchWorkflow(_id: string, _payload: unknown) {{ return {{ ok: true }} }}\n"),
        _ if path == "server/generated/integrations.ts" => format!("{RUST_EMIT_BANNER}export async function callIntegration(_id: string, _payload: unknown) {{ return {{ ok: true }} }}\n"),
        _ => format!("{RUST_EMIT_BANNER}export const generated = {}\n", js_str(path)),
    }
}

fn emit_next_file(graph: &AppGraph, file: &PlannedFile) -> String {
    let path = file.path.as_str();
    match path {
        "package.json" => next_package_json(graph),
        "tsconfig.json" => next_tsconfig(),
        "next.config.mjs" => "/** @type {import('next').NextConfig} */\nconst nextConfig = {}\nexport default nextConfig\n".to_string(),
        "next-env.d.ts" => "/// <reference types=\"next\" />\n/// <reference types=\"next/image-types/global\" />\n".to_string(),
        "postcss.config.mjs" => "const config = {}\nexport default config\n".to_string(),
        "tailwind.config.ts" => "import type { Config } from 'tailwindcss'\n\nexport default { content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'] } satisfies Config\n".to_string(),
        "app/globals.css" => "body { margin: 0; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }\n* { box-sizing: border-box; }\n".to_string(),
        "app/error.tsx" => "'use client'\n\nexport default function Error() { return <main style={{ padding: 24 }}>The page could not render.</main> }\n".to_string(),
        "app/layout.tsx" => next_layout(graph),
        "middleware.ts" => format!("{RUST_EMIT_BANNER}import {{ NextResponse }} from 'next/server'\n\nexport function middleware() {{ return NextResponse.next() }}\n"),
        "components.json" => "{\n  \"style\": \"default\",\n  \"tsx\": true\n}\n".to_string(),
        ".gitignore" => "node_modules\n.next\n.env\n".to_string(),
        ".env.example" => "DB_URL=file:./data.db\nINTENTSTACK_AUTO_MIGRATE=false\n".to_string(),
        "README.md" => generated_readme(graph, "Next.js App Router"),
        "lib/utils.ts" => format!("{RUST_EMIT_BANNER}export function cn(...classes: Array<string | false | null | undefined>) {{ return classes.filter(Boolean).join(' ') }}\n"),
        "lib/otel.ts" => format!("{RUST_EMIT_BANNER}export function nowNanos() {{ return String(Date.now() * 1000000) }}\nexport async function exportSpan(_span: unknown) {{}}\n"),
        "lib/api/client.ts" => api_client_ts(),
        "lib/db/schema.ts" => db_schema_ts(graph),
        "lib/db/client.ts" => db_client_ts(),
        "lib/db/migrate.ts" => format!("{RUST_EMIT_BANNER}import {{ runIntentStackMigrations }} from './client'\n\nawait runIntentStackMigrations()\n"),
        "lib/auth.ts" => format!("{RUST_EMIT_BANNER}export async function currentUser() {{ return null }}\nexport function assertRole() {{}}\n"),
        "lib/workflows.ts" => format!("{RUST_EMIT_BANNER}export async function dispatchWorkflow(_id: string, _payload: unknown) {{ return {{ ok: true }} }}\n"),
        "lib/integrations.ts" => format!("{RUST_EMIT_BANNER}export async function callIntegration(_id: string, _payload: unknown) {{ return {{ ok: true }} }}\n"),
        "app/api/health/route.ts" => next_json_route("{ ok: true }"),
        "app/api/metrics/route.ts" => next_json_route("{ requests_total: 0 }"),
        "migrations/0000_init.sql" => migration_sql(graph),
        "migrations/manifest.json" => migration_manifest_json(graph),
        "components/ui/button.tsx" => ui_primitive("Button", "button"),
        "components/ui/input.tsx" => ui_primitive("Input", "input"),
        "components/ui/textarea.tsx" => ui_primitive("Textarea", "textarea"),
        "components/ui/card.tsx" => ui_card(),
        "components/ui/table.tsx" => ui_table(),
        "components/generated/ProtectedPage.tsx" => format!("{RUST_EMIT_BANNER}import type {{ ReactNode }} from 'react'\n\nexport function ProtectedPage(props: {{ children: ReactNode }}) {{ return <>{{props.children}}</> }}\n"),
        _ if path.starts_with("app/api/") => next_api_route(graph, path),
        _ if path.starts_with("app/") && path.ends_with("page.tsx") => next_page_tsx(graph, path),
        _ if path.starts_with("components/generated/") => next_component_file(graph, path),
        _ if path.starts_with("lib/validators/") => validator_ts(graph, path),
        _ => format!("{RUST_EMIT_BANNER}export const generated = {}\n", js_str(path)),
    }
}

fn web_package_json(graph: &AppGraph) -> String {
    format!(
        r#"{{
  "name": {},
  "version": "0.1.0",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "typecheck": "tsc --noEmit",
    "start": "tsx server/index.ts",
    "migrate": "tsx server/generated/db/migrate.ts"
  }},
  "dependencies": {{
    "@vitejs/plugin-react": "^4.3.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "vite": "^5.4.11"
  }},
  "devDependencies": {{
    "@types/node": "^22.10.1",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "tsx": "^4.19.2",
    "typescript": "^5.6.3"
  }}
}}
"#,
        js_str(&package_name(graph))
    )
}

fn next_package_json(graph: &AppGraph) -> String {
    format!(
        r#"{{
  "name": {},
  "version": "0.1.0",
  "type": "module",
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "typecheck": "tsc --noEmit",
    "migrate": "tsx lib/db/migrate.ts"
  }},
  "dependencies": {{
    "next": "^15.0.3",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  }},
  "devDependencies": {{
    "@types/node": "^22.10.1",
    "@types/react": "^19.0.1",
    "@types/react-dom": "^19.0.2",
    "tsx": "^4.19.2",
    "typescript": "^5.6.3"
  }}
}}
"#,
        js_str(&package_name(graph))
    )
}

fn web_tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src", "server"]
}
"#
    .to_string()
}

fn next_tsconfig() -> String {
    r#"{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "baseUrl": ".",
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "app", "components", "lib"]
}
"#
    .to_string()
}

fn web_routes_tsx(graph: &AppGraph) -> String {
    let imports = graph
        .pages
        .iter()
        .map(|page| {
            format!(
                "import {{ {}Page }} from './generated/pages/{}Page'",
                pascal(&page.id),
                pascal(&page.id)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let branches = graph
        .pages
        .iter()
        .skip(1)
        .map(|page| {
            format!(
                "  if (path === {}) return <{}Page />",
                js_str(&page.path),
                pascal(&page.id)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let first = graph
        .pages
        .first()
        .map(|page| pascal(&page.id))
        .unwrap_or_else(|| "Home".to_string());
    format!(
        "{RUST_EMIT_BANNER}{imports}\n\nexport function App() {{\n  const path = window.location.pathname\n{branches}\n  return <{first}Page />\n}}\n"
    )
}
