/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { drizzle } from "drizzle-orm/libsql";
import { createClient } from "@libsql/client";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const url = process.env.DB_URL ?? "file:./data.db";
export const client = createClient({ url });
export const db = drizzle(client);

let migrated: Promise<unknown> | null = null;
export function ensureMigrated() {
  if (!migrated) {
    const sql = readFileSync(
      join(process.cwd(), "migrations/0000_init.sql"),
      "utf8",
    );
    migrated = client.executeMultiple(sql);
  }
  return migrated;
}
