/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { sqliteTable, integer, text, real } from 'drizzle-orm/sqlite-core'

export const demorequest = sqliteTable('demo_requests', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  email: text('email').notNull(),
  project_type: text('project_type').notNull(),
  budget: real('budget'),
  message: text('message'),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
})
