/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
export async function createLead(payload: Record<string, unknown>) {
  const res = await fetch('/api/leads', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  })
  const json = await res.json().catch(() => ({}))
  return { ok: res.ok, data: json.data, error: json.error }
}

export async function listLead(): Promise<Array<Record<string, unknown>>> {
  const res = await fetch('/api/leads', { cache: 'no-store' })
  const json = await res.json().catch(() => ({ data: [] }))
  return (json.data ?? []) as Array<Record<string, unknown>>
}

export async function getLead(id: number): Promise<{ ok: boolean; data?: Record<string, unknown>; error?: unknown }> {
  const res = await fetch('/api/leads/' + id, { cache: 'no-store' })
  const json = await res.json().catch(() => ({}))
  return { ok: res.ok, data: json.data, error: json.error }
}

export async function updateLead(id: number, payload: Record<string, unknown>) {
  const res = await fetch('/api/leads/' + id, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload),
  })
  const json = await res.json().catch(() => ({}))
  return { ok: res.ok, data: json.data, error: json.error }
}

