/**
 * @generated by IntentStack (target: web_ts_minimal). DO NOT EDIT BY HAND.
 * Source of truth: intent/app.intent.yaml — re-run `intentstack build` to regenerate.
 */
import { Routes, Route } from 'react-router-dom'
import { HomePage } from './generated/pages/HomePage'
import { DocsPage } from './generated/pages/DocsPage'

export function AppRoutes() {
  return (
    <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/docs" element={<DocsPage />} />
    </Routes>
  )
}
