/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { Nav } from '@/components/generated/Nav'
import { Hero } from '@/components/generated/Hero'
import { Features } from '@/components/generated/Features'
import { LeadForm } from '@/components/generated/LeadForm'
import { Footer } from '@/components/generated/Footer'


export default function Page() {
  return (
    <main className="min-h-screen bg-background">
      <Nav />
      <Hero />
      <Features />
      <LeadForm />
      <Footer />
    </main>
  )
}
