/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT — edit intent/app.intent.yaml and rebuild. */
import { z } from 'zod'

export const demorequestCreateSchema = z.object({
  name: z.string().min(1),
  email: z.string().min(1),
  project_type: z.enum(['interior', 'product', 'animation']),
  budget: z.coerce.number().optional(),
  message: z.string().optional(),
})

export type DemoRequestCreate = z.infer<typeof demorequestCreateSchema>
