/**
 * @generated by IntentStack (target: web_ts_minimal). DO NOT EDIT BY HAND.
 * Source of truth: intent/app.intent.yaml - re-run `intentstack build` to regenerate.
 */
import { serve } from '@hono/node-server'
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { randomUUID } from 'node:crypto'
import { migrate } from './generated/db/client'
import { exportSpan, nowNanos } from './generated/otel'
import leadRoutes from './generated/routes/lead'

const metrics = {
  started_at: new Date().toISOString(),
  requests_total: 0,
  requests_by_path: {} as Record<string, number>,
  last_request: null as null | { method: string; path: string; status: number; duration_ms: number; trace_id: string },
}
const app = new Hono()
app.use('/api/*', cors({ origin: (origin) => origin || '*', credentials: true }))
app.use('/api/*', async (c, next) => {
  c.header('Content-Security-Policy', contentSecurityPolicy())
  await next()
})
app.use('/api/*', async (c, next) => {
  const requestId = c.req.header('x-request-id') || randomUUID()
  const correlationId = c.req.header('x-correlation-id') || requestId
  const traceId = traceIdFromHeader(c.req.header('traceparent')) || newTraceId()
  const spanId = newSpanId()
  const startedAt = Date.now()
  const startNanos = nowNanos()
  c.header('X-Request-Id', requestId)
  c.header('X-Correlation-Id', correlationId)
  c.header('X-Trace-Id', traceId)
  c.header('traceparent', `00-${traceId}-${spanId}-01`)
  try {
    await next()
  } finally {
    const path = new URL(c.req.url).pathname
    const duration = Date.now() - startedAt
    metrics.requests_total += 1
    metrics.requests_by_path[path] = (metrics.requests_by_path[path] || 0) + 1
    metrics.last_request = { method: c.req.method, path, status: c.res.status, duration_ms: duration, trace_id: traceId }
    console.log(JSON.stringify({
      level: 'info',
      type: 'http_request',
      request_id: requestId,
      correlation_id: correlationId,
      trace_id: traceId,
      span_id: spanId,
      method: c.req.method,
      path,
      status: c.res.status,
      duration_ms: duration,
    }))
    void exportSpan({
      name: `${c.req.method} ${path}`,
      traceId,
      spanId,
      startTimeUnixNano: startNanos,
      endTimeUnixNano: nowNanos(),
      attributes: {
        'http.request.method': c.req.method,
        'url.path': path,
        'http.response.status_code': c.res.status,
        'intentstack.request_id': requestId,
        'intentstack.correlation_id': correlationId,
      },
    })
  }
})
app.onError((err, c) => {
  const requestId = c.req.header('x-request-id') || randomUUID()
  const correlationId = c.req.header('x-correlation-id') || requestId
  const traceId = traceIdFromHeader(c.req.header('traceparent')) || newTraceId()
  console.error(JSON.stringify({
    level: 'error',
    type: 'http_error',
    request_id: requestId,
    correlation_id: correlationId,
    trace_id: traceId,
    method: c.req.method,
    path: new URL(c.req.url).pathname,
    message: err.message,
  }))
  return c.json({ error: 'internal_error', request_id: requestId, correlation_id: correlationId, trace_id: traceId }, 500)
})
app.get('/api/health', (c) => c.json({ ok: true }))
app.get('/api/metrics', (c) => c.json({
  ok: true,
  uptime_seconds: process.uptime(),
  ...metrics,
}))
app.route('/api', leadRoutes)

const port = Number(process.env.PORT ?? 8787)
await migrate()
const server = serve({ fetch: app.fetch, port })

console.log(`[intentstack] API listening on http://localhost:${port}`)

function newTraceId() {
  return randomUUID().replace(/-/g, '')
}

function newSpanId() {
  return randomUUID().replace(/-/g, '').slice(0, 16)
}

function traceIdFromHeader(value: string | undefined) {
  const match = /^00-([a-f0-9]{32})-[a-f0-9]{16}-[a-f0-9]{2}$/i.exec(value || '')
  return match?.[1]?.toLowerCase() || ''
}

function contentSecurityPolicy() {
  return [
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "connect-src 'self' http://localhost:* ws://localhost:*",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "base-uri 'self'",
  ].join('; ')
}

function shutdown(signal: NodeJS.Signals) {
  console.log(JSON.stringify({ level: 'info', type: 'shutdown', signal }))
  server.close((err) => {
    if (err) {
      console.error(JSON.stringify({ level: 'error', type: 'shutdown_error', message: err.message }))
      process.exit(1)
    }
    process.exit(0)
  })
}

process.once('SIGINT', shutdown)
process.once('SIGTERM', shutdown)
