-- @generated by IntentStack. Applied automatically on server start.

CREATE TABLE IF NOT EXISTS leads (
  id integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  company text,
  message text,
  status text DEFAULT 'new',
  created_at integer NOT NULL
);

