export const BANNER = '/* @generated by IntentStack (target: next_shadcn). DO NOT EDIT - edit intent/app.intent.yaml and rebuild. */\n'

const RADIUS_REM = { none: '0rem', sm: '0.25rem', md: '0.5rem', lg: '0.75rem', xl: '1rem', full: '9999px' }
const PAD = { compact: 'py-12', comfortable: 'py-20', spacious: 'py-28' }

export const radiusVar = (theme) => RADIUS_REM[theme?.radius] || '0.5rem'
export const pad = (theme) => PAD[theme?.density] || 'py-20'
